/*
 * API REST INTERNA de DigitalIB
 * Conjunt de Serveis REST de DigitalIB per ser accedits des de l'interior
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: otae@fundaciobit.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.digitalib.apiinterna.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * MassiveScanWebSimpleConstants
 */
@JsonPropertyOrder({
  MassiveScanWebSimpleConstants.JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_GET_TRANSACTION_ID_REQUEST_V_I_E_W_F_U_L_L_S_C_R_E_E_N,
  MassiveScanWebSimpleConstants.JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_GET_TRANSACTION_ID_REQUEST_V_I_E_W_I_F_R_A_M_E,
  MassiveScanWebSimpleConstants.JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_AVAILABLE_PROFILE_P_R_O_F_I_L_E_T_Y_P_E_O_N_L_Y_S_C_A_N,
  MassiveScanWebSimpleConstants.JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_AVAILABLE_PROFILE_P_R_O_F_I_L_E_T_Y_P_E_S_C_A_N_A_N_D_S_I_G_N_A_T_U_R_E,
  MassiveScanWebSimpleConstants.JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_AVAILABLE_PROFILE_P_R_O_F_I_L_E_T_Y_P_E_S_C_A_N_A_N_D_S_I_G_N_A_T_U_R_E_A_N_D_C_U_S_T_O_D_Y,
  MassiveScanWebSimpleConstants.JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_STATUS_S_T_A_T_U_S_R_E_Q_U_E_S_T_E_D_I_D,
  MassiveScanWebSimpleConstants.JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_STATUS_S_T_A_T_U_S_I_N_P_R_O_G_R_E_S_S,
  MassiveScanWebSimpleConstants.JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_STATUS_S_T_A_T_U_S_F_I_N_A_L_O_K,
  MassiveScanWebSimpleConstants.JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_STATUS_S_T_A_T_U_S_F_I_N_A_L_E_R_R_O_R,
  MassiveScanWebSimpleConstants.JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_STATUS_S_T_A_T_U_S_C_A_N_C_E_L_L_E_D,
  MassiveScanWebSimpleConstants.JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_STATUS_S_T_A_T_U_S_E_X_P_I_R_E_D,
  MassiveScanWebSimpleConstants.JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_ARXIU_REQUIRED_PARAMETERS_D_O_C_U_M_E_N_T_O_R_I_G_E_N_C_I_U_T_A_D_A,
  MassiveScanWebSimpleConstants.JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_ARXIU_REQUIRED_PARAMETERS_D_O_C_U_M_E_N_T_O_R_I_G_E_N_A_D_M_I_N_I_S_T_R_A_C_I_O,
  MassiveScanWebSimpleConstants.JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_ARXIU_REQUIRED_PARAMETERS_D_O_C_U_M_E_N_T_E_L_A_B_O_R_A_T_I_O_N_S_T_A_T_E_O_R_I_G_I_N_A_L,
  MassiveScanWebSimpleConstants.JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_ARXIU_REQUIRED_PARAMETERS_D_O_C_U_M_E_N_T_E_L_A_B_O_R_A_T_I_O_N_S_T_A_T_E_C_O_P_I_A_C_F,
  MassiveScanWebSimpleConstants.JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_ARXIU_REQUIRED_PARAMETERS_D_O_C_U_M_E_N_T_E_L_A_B_O_R_A_T_I_O_N_S_T_A_T_E_C_O_P_I_A_D_P,
  MassiveScanWebSimpleConstants.JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_ARXIU_REQUIRED_PARAMETERS_D_O_C_U_M_E_N_T_E_L_A_B_O_R_A_T_I_O_N_S_T_A_T_E_C_O_P_I_A_P_R,
  MassiveScanWebSimpleConstants.JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_ARXIU_REQUIRED_PARAMETERS_D_O_C_U_M_E_N_T_E_L_A_B_O_R_A_T_I_O_N_S_T_A_T_E_A_L_T_R_E_S,
  MassiveScanWebSimpleConstants.JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_SCANNED_FILE_INFO_F_O_R_M_A_T_F_I_L_E_P_D_F,
  MassiveScanWebSimpleConstants.JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_SCANNED_FILE_INFO_F_O_R_M_A_T_F_I_L_E_J_P_G,
  MassiveScanWebSimpleConstants.JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_SCANNED_FILE_INFO_F_O_R_M_A_T_F_I_L_E_T_I_F_F,
  MassiveScanWebSimpleConstants.JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_SCANNED_FILE_INFO_F_O_R_M_A_T_F_I_L_E_P_N_G,
  MassiveScanWebSimpleConstants.JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_SCANNED_FILE_INFO_F_O_R_M_A_T_F_I_L_E_G_I_F,
  MassiveScanWebSimpleConstants.JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_SCANNED_FILE_INFO_P_I_X_E_L_T_Y_P_E_B_L_A_C_K_W_H_I_T_E,
  MassiveScanWebSimpleConstants.JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_SCANNED_FILE_INFO_P_I_X_E_L_T_Y_P_E_G_R_A_Y,
  MassiveScanWebSimpleConstants.JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_SCANNED_FILE_INFO_P_I_X_E_L_T_Y_P_E_C_O_L_O_R
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.4.0")
public class MassiveScanWebSimpleConstants {
  public static final String JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_GET_TRANSACTION_ID_REQUEST_V_I_E_W_F_U_L_L_S_C_R_E_E_N = "MassiveScanWebSimpleGetTransactionIdRequest_VIEW_FULLSCREEN";
  private Integer massiveScanWebSimpleGetTransactionIdRequestVIEWFULLSCREEN = 0;

  public static final String JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_GET_TRANSACTION_ID_REQUEST_V_I_E_W_I_F_R_A_M_E = "MassiveScanWebSimpleGetTransactionIdRequest_VIEW_IFRAME";
  private Integer massiveScanWebSimpleGetTransactionIdRequestVIEWIFRAME = 1;

  public static final String JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_AVAILABLE_PROFILE_P_R_O_F_I_L_E_T_Y_P_E_O_N_L_Y_S_C_A_N = "MassiveScanWebSimpleAvailableProfile_PROFILE_TYPE_ONLY_SCAN";
  private Integer massiveScanWebSimpleAvailableProfilePROFILETYPEONLYSCAN = 1;

  public static final String JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_AVAILABLE_PROFILE_P_R_O_F_I_L_E_T_Y_P_E_S_C_A_N_A_N_D_S_I_G_N_A_T_U_R_E = "MassiveScanWebSimpleAvailableProfile_PROFILE_TYPE_SCAN_AND_SIGNATURE";
  private Integer massiveScanWebSimpleAvailableProfilePROFILETYPESCANANDSIGNATURE = 2;

  public static final String JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_AVAILABLE_PROFILE_P_R_O_F_I_L_E_T_Y_P_E_S_C_A_N_A_N_D_S_I_G_N_A_T_U_R_E_A_N_D_C_U_S_T_O_D_Y = "MassiveScanWebSimpleAvailableProfile_PROFILE_TYPE_SCAN_AND_SIGNATURE_AND_CUSTODY";
  private Integer massiveScanWebSimpleAvailableProfilePROFILETYPESCANANDSIGNATUREANDCUSTODY = 3;

  public static final String JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_STATUS_S_T_A_T_U_S_R_E_Q_U_E_S_T_E_D_I_D = "MassiveScanWebSimpleStatus_STATUS_REQUESTED_ID";
  private Integer massiveScanWebSimpleStatusSTATUSREQUESTEDID = 0;

  public static final String JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_STATUS_S_T_A_T_U_S_I_N_P_R_O_G_R_E_S_S = "MassiveScanWebSimpleStatus_STATUS_IN_PROGRESS";
  private Integer massiveScanWebSimpleStatusSTATUSINPROGRESS = 1;

  public static final String JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_STATUS_S_T_A_T_U_S_F_I_N_A_L_O_K = "MassiveScanWebSimpleStatus_STATUS_FINAL_OK";
  private Integer massiveScanWebSimpleStatusSTATUSFINALOK = 2;

  public static final String JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_STATUS_S_T_A_T_U_S_F_I_N_A_L_E_R_R_O_R = "MassiveScanWebSimpleStatus_STATUS_FINAL_ERROR";
  private Integer massiveScanWebSimpleStatusSTATUSFINALERROR = -1;

  public static final String JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_STATUS_S_T_A_T_U_S_C_A_N_C_E_L_L_E_D = "MassiveScanWebSimpleStatus_STATUS_CANCELLED";
  private Integer massiveScanWebSimpleStatusSTATUSCANCELLED = -2;

  public static final String JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_STATUS_S_T_A_T_U_S_E_X_P_I_R_E_D = "MassiveScanWebSimpleStatus_STATUS_EXPIRED";
  private Integer massiveScanWebSimpleStatusSTATUSEXPIRED = -3;

  public static final String JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_ARXIU_REQUIRED_PARAMETERS_D_O_C_U_M_E_N_T_O_R_I_G_E_N_C_I_U_T_A_D_A = "MassiveScanWebSimpleArxiuRequiredParameters_DOCUMENTORIGEN_CIUTADA";
  private Integer massiveScanWebSimpleArxiuRequiredParametersDOCUMENTORIGENCIUTADA = 0;

  public static final String JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_ARXIU_REQUIRED_PARAMETERS_D_O_C_U_M_E_N_T_O_R_I_G_E_N_A_D_M_I_N_I_S_T_R_A_C_I_O = "MassiveScanWebSimpleArxiuRequiredParameters_DOCUMENTORIGEN_ADMINISTRACIO";
  private Integer massiveScanWebSimpleArxiuRequiredParametersDOCUMENTORIGENADMINISTRACIO = 1;

  public static final String JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_ARXIU_REQUIRED_PARAMETERS_D_O_C_U_M_E_N_T_E_L_A_B_O_R_A_T_I_O_N_S_T_A_T_E_O_R_I_G_I_N_A_L = "MassiveScanWebSimpleArxiuRequiredParameters_DOCUMENTELABORATIONSTATE_ORIGINAL";
  private String massiveScanWebSimpleArxiuRequiredParametersDOCUMENTELABORATIONSTATEORIGINAL = "EE01";

  public static final String JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_ARXIU_REQUIRED_PARAMETERS_D_O_C_U_M_E_N_T_E_L_A_B_O_R_A_T_I_O_N_S_T_A_T_E_C_O_P_I_A_C_F = "MassiveScanWebSimpleArxiuRequiredParameters_DOCUMENTELABORATIONSTATE_COPIA_CF";
  private String massiveScanWebSimpleArxiuRequiredParametersDOCUMENTELABORATIONSTATECOPIACF = "EE02";

  public static final String JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_ARXIU_REQUIRED_PARAMETERS_D_O_C_U_M_E_N_T_E_L_A_B_O_R_A_T_I_O_N_S_T_A_T_E_C_O_P_I_A_D_P = "MassiveScanWebSimpleArxiuRequiredParameters_DOCUMENTELABORATIONSTATE_COPIA_DP";
  private String massiveScanWebSimpleArxiuRequiredParametersDOCUMENTELABORATIONSTATECOPIADP = "EE03";

  public static final String JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_ARXIU_REQUIRED_PARAMETERS_D_O_C_U_M_E_N_T_E_L_A_B_O_R_A_T_I_O_N_S_T_A_T_E_C_O_P_I_A_P_R = "MassiveScanWebSimpleArxiuRequiredParameters_DOCUMENTELABORATIONSTATE_COPIA_PR";
  private String massiveScanWebSimpleArxiuRequiredParametersDOCUMENTELABORATIONSTATECOPIAPR = "EE04";

  public static final String JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_ARXIU_REQUIRED_PARAMETERS_D_O_C_U_M_E_N_T_E_L_A_B_O_R_A_T_I_O_N_S_T_A_T_E_A_L_T_R_E_S = "MassiveScanWebSimpleArxiuRequiredParameters_DOCUMENTELABORATIONSTATE_ALTRES";
  private String massiveScanWebSimpleArxiuRequiredParametersDOCUMENTELABORATIONSTATEALTRES = "EE99";

  public static final String JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_SCANNED_FILE_INFO_F_O_R_M_A_T_F_I_L_E_P_D_F = "MassiveScanWebSimpleScannedFileInfo_FORMAT_FILE_PDF";
  private String massiveScanWebSimpleScannedFileInfoFORMATFILEPDF = "pdf";

  public static final String JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_SCANNED_FILE_INFO_F_O_R_M_A_T_F_I_L_E_J_P_G = "MassiveScanWebSimpleScannedFileInfo_FORMAT_FILE_JPG";
  private String massiveScanWebSimpleScannedFileInfoFORMATFILEJPG = "jpg";

  public static final String JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_SCANNED_FILE_INFO_F_O_R_M_A_T_F_I_L_E_T_I_F_F = "MassiveScanWebSimpleScannedFileInfo_FORMAT_FILE_TIFF";
  private String massiveScanWebSimpleScannedFileInfoFORMATFILETIFF = "tif";

  public static final String JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_SCANNED_FILE_INFO_F_O_R_M_A_T_F_I_L_E_P_N_G = "MassiveScanWebSimpleScannedFileInfo_FORMAT_FILE_PNG";
  private String massiveScanWebSimpleScannedFileInfoFORMATFILEPNG = "png";

  public static final String JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_SCANNED_FILE_INFO_F_O_R_M_A_T_F_I_L_E_G_I_F = "MassiveScanWebSimpleScannedFileInfo_FORMAT_FILE_GIF";
  private String massiveScanWebSimpleScannedFileInfoFORMATFILEGIF = "gif";

  public static final String JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_SCANNED_FILE_INFO_P_I_X_E_L_T_Y_P_E_B_L_A_C_K_W_H_I_T_E = "MassiveScanWebSimpleScannedFileInfo_PIXEL_TYPE_BLACK_WHITE";
  private Integer massiveScanWebSimpleScannedFileInfoPIXELTYPEBLACKWHITE = 0;

  public static final String JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_SCANNED_FILE_INFO_P_I_X_E_L_T_Y_P_E_G_R_A_Y = "MassiveScanWebSimpleScannedFileInfo_PIXEL_TYPE_GRAY";
  private Integer massiveScanWebSimpleScannedFileInfoPIXELTYPEGRAY = 1;

  public static final String JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_SCANNED_FILE_INFO_P_I_X_E_L_T_Y_P_E_C_O_L_O_R = "MassiveScanWebSimpleScannedFileInfo_PIXEL_TYPE_COLOR";
  private Integer massiveScanWebSimpleScannedFileInfoPIXELTYPECOLOR = 2;

  public MassiveScanWebSimpleConstants() {
  }

  @JsonCreator
  public MassiveScanWebSimpleConstants(
    @JsonProperty(JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_GET_TRANSACTION_ID_REQUEST_V_I_E_W_F_U_L_L_S_C_R_E_E_N) Integer massiveScanWebSimpleGetTransactionIdRequestVIEWFULLSCREEN, 
    @JsonProperty(JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_GET_TRANSACTION_ID_REQUEST_V_I_E_W_I_F_R_A_M_E) Integer massiveScanWebSimpleGetTransactionIdRequestVIEWIFRAME, 
    @JsonProperty(JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_AVAILABLE_PROFILE_P_R_O_F_I_L_E_T_Y_P_E_O_N_L_Y_S_C_A_N) Integer massiveScanWebSimpleAvailableProfilePROFILETYPEONLYSCAN, 
    @JsonProperty(JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_AVAILABLE_PROFILE_P_R_O_F_I_L_E_T_Y_P_E_S_C_A_N_A_N_D_S_I_G_N_A_T_U_R_E) Integer massiveScanWebSimpleAvailableProfilePROFILETYPESCANANDSIGNATURE, 
    @JsonProperty(JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_AVAILABLE_PROFILE_P_R_O_F_I_L_E_T_Y_P_E_S_C_A_N_A_N_D_S_I_G_N_A_T_U_R_E_A_N_D_C_U_S_T_O_D_Y) Integer massiveScanWebSimpleAvailableProfilePROFILETYPESCANANDSIGNATUREANDCUSTODY, 
    @JsonProperty(JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_STATUS_S_T_A_T_U_S_R_E_Q_U_E_S_T_E_D_I_D) Integer massiveScanWebSimpleStatusSTATUSREQUESTEDID, 
    @JsonProperty(JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_STATUS_S_T_A_T_U_S_I_N_P_R_O_G_R_E_S_S) Integer massiveScanWebSimpleStatusSTATUSINPROGRESS, 
    @JsonProperty(JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_STATUS_S_T_A_T_U_S_F_I_N_A_L_O_K) Integer massiveScanWebSimpleStatusSTATUSFINALOK, 
    @JsonProperty(JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_STATUS_S_T_A_T_U_S_F_I_N_A_L_E_R_R_O_R) Integer massiveScanWebSimpleStatusSTATUSFINALERROR, 
    @JsonProperty(JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_STATUS_S_T_A_T_U_S_C_A_N_C_E_L_L_E_D) Integer massiveScanWebSimpleStatusSTATUSCANCELLED, 
    @JsonProperty(JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_STATUS_S_T_A_T_U_S_E_X_P_I_R_E_D) Integer massiveScanWebSimpleStatusSTATUSEXPIRED, 
    @JsonProperty(JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_ARXIU_REQUIRED_PARAMETERS_D_O_C_U_M_E_N_T_O_R_I_G_E_N_C_I_U_T_A_D_A) Integer massiveScanWebSimpleArxiuRequiredParametersDOCUMENTORIGENCIUTADA, 
    @JsonProperty(JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_ARXIU_REQUIRED_PARAMETERS_D_O_C_U_M_E_N_T_O_R_I_G_E_N_A_D_M_I_N_I_S_T_R_A_C_I_O) Integer massiveScanWebSimpleArxiuRequiredParametersDOCUMENTORIGENADMINISTRACIO, 
    @JsonProperty(JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_ARXIU_REQUIRED_PARAMETERS_D_O_C_U_M_E_N_T_E_L_A_B_O_R_A_T_I_O_N_S_T_A_T_E_O_R_I_G_I_N_A_L) String massiveScanWebSimpleArxiuRequiredParametersDOCUMENTELABORATIONSTATEORIGINAL, 
    @JsonProperty(JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_ARXIU_REQUIRED_PARAMETERS_D_O_C_U_M_E_N_T_E_L_A_B_O_R_A_T_I_O_N_S_T_A_T_E_C_O_P_I_A_C_F) String massiveScanWebSimpleArxiuRequiredParametersDOCUMENTELABORATIONSTATECOPIACF, 
    @JsonProperty(JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_ARXIU_REQUIRED_PARAMETERS_D_O_C_U_M_E_N_T_E_L_A_B_O_R_A_T_I_O_N_S_T_A_T_E_C_O_P_I_A_D_P) String massiveScanWebSimpleArxiuRequiredParametersDOCUMENTELABORATIONSTATECOPIADP, 
    @JsonProperty(JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_ARXIU_REQUIRED_PARAMETERS_D_O_C_U_M_E_N_T_E_L_A_B_O_R_A_T_I_O_N_S_T_A_T_E_C_O_P_I_A_P_R) String massiveScanWebSimpleArxiuRequiredParametersDOCUMENTELABORATIONSTATECOPIAPR, 
    @JsonProperty(JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_ARXIU_REQUIRED_PARAMETERS_D_O_C_U_M_E_N_T_E_L_A_B_O_R_A_T_I_O_N_S_T_A_T_E_A_L_T_R_E_S) String massiveScanWebSimpleArxiuRequiredParametersDOCUMENTELABORATIONSTATEALTRES, 
    @JsonProperty(JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_SCANNED_FILE_INFO_F_O_R_M_A_T_F_I_L_E_P_D_F) String massiveScanWebSimpleScannedFileInfoFORMATFILEPDF, 
    @JsonProperty(JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_SCANNED_FILE_INFO_F_O_R_M_A_T_F_I_L_E_J_P_G) String massiveScanWebSimpleScannedFileInfoFORMATFILEJPG, 
    @JsonProperty(JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_SCANNED_FILE_INFO_F_O_R_M_A_T_F_I_L_E_T_I_F_F) String massiveScanWebSimpleScannedFileInfoFORMATFILETIFF, 
    @JsonProperty(JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_SCANNED_FILE_INFO_F_O_R_M_A_T_F_I_L_E_P_N_G) String massiveScanWebSimpleScannedFileInfoFORMATFILEPNG, 
    @JsonProperty(JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_SCANNED_FILE_INFO_F_O_R_M_A_T_F_I_L_E_G_I_F) String massiveScanWebSimpleScannedFileInfoFORMATFILEGIF, 
    @JsonProperty(JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_SCANNED_FILE_INFO_P_I_X_E_L_T_Y_P_E_B_L_A_C_K_W_H_I_T_E) Integer massiveScanWebSimpleScannedFileInfoPIXELTYPEBLACKWHITE, 
    @JsonProperty(JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_SCANNED_FILE_INFO_P_I_X_E_L_T_Y_P_E_G_R_A_Y) Integer massiveScanWebSimpleScannedFileInfoPIXELTYPEGRAY, 
    @JsonProperty(JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_SCANNED_FILE_INFO_P_I_X_E_L_T_Y_P_E_C_O_L_O_R) Integer massiveScanWebSimpleScannedFileInfoPIXELTYPECOLOR
  ) {
    this();
    this.massiveScanWebSimpleGetTransactionIdRequestVIEWFULLSCREEN = massiveScanWebSimpleGetTransactionIdRequestVIEWFULLSCREEN;
    this.massiveScanWebSimpleGetTransactionIdRequestVIEWIFRAME = massiveScanWebSimpleGetTransactionIdRequestVIEWIFRAME;
    this.massiveScanWebSimpleAvailableProfilePROFILETYPEONLYSCAN = massiveScanWebSimpleAvailableProfilePROFILETYPEONLYSCAN;
    this.massiveScanWebSimpleAvailableProfilePROFILETYPESCANANDSIGNATURE = massiveScanWebSimpleAvailableProfilePROFILETYPESCANANDSIGNATURE;
    this.massiveScanWebSimpleAvailableProfilePROFILETYPESCANANDSIGNATUREANDCUSTODY = massiveScanWebSimpleAvailableProfilePROFILETYPESCANANDSIGNATUREANDCUSTODY;
    this.massiveScanWebSimpleStatusSTATUSREQUESTEDID = massiveScanWebSimpleStatusSTATUSREQUESTEDID;
    this.massiveScanWebSimpleStatusSTATUSINPROGRESS = massiveScanWebSimpleStatusSTATUSINPROGRESS;
    this.massiveScanWebSimpleStatusSTATUSFINALOK = massiveScanWebSimpleStatusSTATUSFINALOK;
    this.massiveScanWebSimpleStatusSTATUSFINALERROR = massiveScanWebSimpleStatusSTATUSFINALERROR;
    this.massiveScanWebSimpleStatusSTATUSCANCELLED = massiveScanWebSimpleStatusSTATUSCANCELLED;
    this.massiveScanWebSimpleStatusSTATUSEXPIRED = massiveScanWebSimpleStatusSTATUSEXPIRED;
    this.massiveScanWebSimpleArxiuRequiredParametersDOCUMENTORIGENCIUTADA = massiveScanWebSimpleArxiuRequiredParametersDOCUMENTORIGENCIUTADA;
    this.massiveScanWebSimpleArxiuRequiredParametersDOCUMENTORIGENADMINISTRACIO = massiveScanWebSimpleArxiuRequiredParametersDOCUMENTORIGENADMINISTRACIO;
    this.massiveScanWebSimpleArxiuRequiredParametersDOCUMENTELABORATIONSTATEORIGINAL = massiveScanWebSimpleArxiuRequiredParametersDOCUMENTELABORATIONSTATEORIGINAL;
    this.massiveScanWebSimpleArxiuRequiredParametersDOCUMENTELABORATIONSTATECOPIACF = massiveScanWebSimpleArxiuRequiredParametersDOCUMENTELABORATIONSTATECOPIACF;
    this.massiveScanWebSimpleArxiuRequiredParametersDOCUMENTELABORATIONSTATECOPIADP = massiveScanWebSimpleArxiuRequiredParametersDOCUMENTELABORATIONSTATECOPIADP;
    this.massiveScanWebSimpleArxiuRequiredParametersDOCUMENTELABORATIONSTATECOPIAPR = massiveScanWebSimpleArxiuRequiredParametersDOCUMENTELABORATIONSTATECOPIAPR;
    this.massiveScanWebSimpleArxiuRequiredParametersDOCUMENTELABORATIONSTATEALTRES = massiveScanWebSimpleArxiuRequiredParametersDOCUMENTELABORATIONSTATEALTRES;
    this.massiveScanWebSimpleScannedFileInfoFORMATFILEPDF = massiveScanWebSimpleScannedFileInfoFORMATFILEPDF;
    this.massiveScanWebSimpleScannedFileInfoFORMATFILEJPG = massiveScanWebSimpleScannedFileInfoFORMATFILEJPG;
    this.massiveScanWebSimpleScannedFileInfoFORMATFILETIFF = massiveScanWebSimpleScannedFileInfoFORMATFILETIFF;
    this.massiveScanWebSimpleScannedFileInfoFORMATFILEPNG = massiveScanWebSimpleScannedFileInfoFORMATFILEPNG;
    this.massiveScanWebSimpleScannedFileInfoFORMATFILEGIF = massiveScanWebSimpleScannedFileInfoFORMATFILEGIF;
    this.massiveScanWebSimpleScannedFileInfoPIXELTYPEBLACKWHITE = massiveScanWebSimpleScannedFileInfoPIXELTYPEBLACKWHITE;
    this.massiveScanWebSimpleScannedFileInfoPIXELTYPEGRAY = massiveScanWebSimpleScannedFileInfoPIXELTYPEGRAY;
    this.massiveScanWebSimpleScannedFileInfoPIXELTYPECOLOR = massiveScanWebSimpleScannedFileInfoPIXELTYPECOLOR;
  }

   /**
   * Constant MassiveScanWebSimpleGetTransactionIdRequest_VIEW_FULLSCREEN
   * @return massiveScanWebSimpleGetTransactionIdRequestVIEWFULLSCREEN
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_GET_TRANSACTION_ID_REQUEST_V_I_E_W_F_U_L_L_S_C_R_E_E_N)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getMassiveScanWebSimpleGetTransactionIdRequestVIEWFULLSCREEN() {
    return massiveScanWebSimpleGetTransactionIdRequestVIEWFULLSCREEN;
  }




   /**
   * Constant MassiveScanWebSimpleGetTransactionIdRequest_VIEW_IFRAME
   * @return massiveScanWebSimpleGetTransactionIdRequestVIEWIFRAME
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_GET_TRANSACTION_ID_REQUEST_V_I_E_W_I_F_R_A_M_E)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getMassiveScanWebSimpleGetTransactionIdRequestVIEWIFRAME() {
    return massiveScanWebSimpleGetTransactionIdRequestVIEWIFRAME;
  }




   /**
   * Constant MassiveScanWebSimpleAvailableProfile_PROFILE_TYPE_ONLY_SCAN
   * @return massiveScanWebSimpleAvailableProfilePROFILETYPEONLYSCAN
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_AVAILABLE_PROFILE_P_R_O_F_I_L_E_T_Y_P_E_O_N_L_Y_S_C_A_N)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getMassiveScanWebSimpleAvailableProfilePROFILETYPEONLYSCAN() {
    return massiveScanWebSimpleAvailableProfilePROFILETYPEONLYSCAN;
  }




   /**
   * Constant MassiveScanWebSimpleAvailableProfile_PROFILE_TYPE_SCAN_AND_SIGNATURE
   * @return massiveScanWebSimpleAvailableProfilePROFILETYPESCANANDSIGNATURE
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_AVAILABLE_PROFILE_P_R_O_F_I_L_E_T_Y_P_E_S_C_A_N_A_N_D_S_I_G_N_A_T_U_R_E)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getMassiveScanWebSimpleAvailableProfilePROFILETYPESCANANDSIGNATURE() {
    return massiveScanWebSimpleAvailableProfilePROFILETYPESCANANDSIGNATURE;
  }




   /**
   * Constant MassiveScanWebSimpleAvailableProfile_PROFILE_TYPE_SCAN_AND_SIGNATURE_AND_CUSTODY
   * @return massiveScanWebSimpleAvailableProfilePROFILETYPESCANANDSIGNATUREANDCUSTODY
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_AVAILABLE_PROFILE_P_R_O_F_I_L_E_T_Y_P_E_S_C_A_N_A_N_D_S_I_G_N_A_T_U_R_E_A_N_D_C_U_S_T_O_D_Y)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getMassiveScanWebSimpleAvailableProfilePROFILETYPESCANANDSIGNATUREANDCUSTODY() {
    return massiveScanWebSimpleAvailableProfilePROFILETYPESCANANDSIGNATUREANDCUSTODY;
  }




   /**
   * Constant MassiveScanWebSimpleStatus_STATUS_REQUESTED_ID
   * @return massiveScanWebSimpleStatusSTATUSREQUESTEDID
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_STATUS_S_T_A_T_U_S_R_E_Q_U_E_S_T_E_D_I_D)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getMassiveScanWebSimpleStatusSTATUSREQUESTEDID() {
    return massiveScanWebSimpleStatusSTATUSREQUESTEDID;
  }




   /**
   * Constant MassiveScanWebSimpleStatus_STATUS_IN_PROGRESS
   * @return massiveScanWebSimpleStatusSTATUSINPROGRESS
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_STATUS_S_T_A_T_U_S_I_N_P_R_O_G_R_E_S_S)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getMassiveScanWebSimpleStatusSTATUSINPROGRESS() {
    return massiveScanWebSimpleStatusSTATUSINPROGRESS;
  }




   /**
   * Constant MassiveScanWebSimpleStatus_STATUS_FINAL_OK
   * @return massiveScanWebSimpleStatusSTATUSFINALOK
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_STATUS_S_T_A_T_U_S_F_I_N_A_L_O_K)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getMassiveScanWebSimpleStatusSTATUSFINALOK() {
    return massiveScanWebSimpleStatusSTATUSFINALOK;
  }




   /**
   * Constant MassiveScanWebSimpleStatus_STATUS_FINAL_ERROR
   * @return massiveScanWebSimpleStatusSTATUSFINALERROR
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_STATUS_S_T_A_T_U_S_F_I_N_A_L_E_R_R_O_R)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getMassiveScanWebSimpleStatusSTATUSFINALERROR() {
    return massiveScanWebSimpleStatusSTATUSFINALERROR;
  }




   /**
   * Constant MassiveScanWebSimpleStatus_STATUS_CANCELLED
   * @return massiveScanWebSimpleStatusSTATUSCANCELLED
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_STATUS_S_T_A_T_U_S_C_A_N_C_E_L_L_E_D)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getMassiveScanWebSimpleStatusSTATUSCANCELLED() {
    return massiveScanWebSimpleStatusSTATUSCANCELLED;
  }




   /**
   * Constant MassiveScanWebSimpleStatus_STATUS_EXPIRED
   * @return massiveScanWebSimpleStatusSTATUSEXPIRED
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_STATUS_S_T_A_T_U_S_E_X_P_I_R_E_D)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getMassiveScanWebSimpleStatusSTATUSEXPIRED() {
    return massiveScanWebSimpleStatusSTATUSEXPIRED;
  }




   /**
   * Constant MassiveScanWebSimpleArxiuRequiredParameters_DOCUMENTORIGEN_CIUTADA
   * @return massiveScanWebSimpleArxiuRequiredParametersDOCUMENTORIGENCIUTADA
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_ARXIU_REQUIRED_PARAMETERS_D_O_C_U_M_E_N_T_O_R_I_G_E_N_C_I_U_T_A_D_A)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getMassiveScanWebSimpleArxiuRequiredParametersDOCUMENTORIGENCIUTADA() {
    return massiveScanWebSimpleArxiuRequiredParametersDOCUMENTORIGENCIUTADA;
  }




   /**
   * Constant MassiveScanWebSimpleArxiuRequiredParameters_DOCUMENTORIGEN_ADMINISTRACIO
   * @return massiveScanWebSimpleArxiuRequiredParametersDOCUMENTORIGENADMINISTRACIO
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_ARXIU_REQUIRED_PARAMETERS_D_O_C_U_M_E_N_T_O_R_I_G_E_N_A_D_M_I_N_I_S_T_R_A_C_I_O)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getMassiveScanWebSimpleArxiuRequiredParametersDOCUMENTORIGENADMINISTRACIO() {
    return massiveScanWebSimpleArxiuRequiredParametersDOCUMENTORIGENADMINISTRACIO;
  }




   /**
   * Constant MassiveScanWebSimpleArxiuRequiredParameters_DOCUMENTELABORATIONSTATE_ORIGINAL
   * @return massiveScanWebSimpleArxiuRequiredParametersDOCUMENTELABORATIONSTATEORIGINAL
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_ARXIU_REQUIRED_PARAMETERS_D_O_C_U_M_E_N_T_E_L_A_B_O_R_A_T_I_O_N_S_T_A_T_E_O_R_I_G_I_N_A_L)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getMassiveScanWebSimpleArxiuRequiredParametersDOCUMENTELABORATIONSTATEORIGINAL() {
    return massiveScanWebSimpleArxiuRequiredParametersDOCUMENTELABORATIONSTATEORIGINAL;
  }




   /**
   * Constant MassiveScanWebSimpleArxiuRequiredParameters_DOCUMENTELABORATIONSTATE_COPIA_CF
   * @return massiveScanWebSimpleArxiuRequiredParametersDOCUMENTELABORATIONSTATECOPIACF
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_ARXIU_REQUIRED_PARAMETERS_D_O_C_U_M_E_N_T_E_L_A_B_O_R_A_T_I_O_N_S_T_A_T_E_C_O_P_I_A_C_F)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getMassiveScanWebSimpleArxiuRequiredParametersDOCUMENTELABORATIONSTATECOPIACF() {
    return massiveScanWebSimpleArxiuRequiredParametersDOCUMENTELABORATIONSTATECOPIACF;
  }




   /**
   * Constant MassiveScanWebSimpleArxiuRequiredParameters_DOCUMENTELABORATIONSTATE_COPIA_DP
   * @return massiveScanWebSimpleArxiuRequiredParametersDOCUMENTELABORATIONSTATECOPIADP
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_ARXIU_REQUIRED_PARAMETERS_D_O_C_U_M_E_N_T_E_L_A_B_O_R_A_T_I_O_N_S_T_A_T_E_C_O_P_I_A_D_P)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getMassiveScanWebSimpleArxiuRequiredParametersDOCUMENTELABORATIONSTATECOPIADP() {
    return massiveScanWebSimpleArxiuRequiredParametersDOCUMENTELABORATIONSTATECOPIADP;
  }




   /**
   * Constant MassiveScanWebSimpleArxiuRequiredParameters_DOCUMENTELABORATIONSTATE_COPIA_PR
   * @return massiveScanWebSimpleArxiuRequiredParametersDOCUMENTELABORATIONSTATECOPIAPR
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_ARXIU_REQUIRED_PARAMETERS_D_O_C_U_M_E_N_T_E_L_A_B_O_R_A_T_I_O_N_S_T_A_T_E_C_O_P_I_A_P_R)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getMassiveScanWebSimpleArxiuRequiredParametersDOCUMENTELABORATIONSTATECOPIAPR() {
    return massiveScanWebSimpleArxiuRequiredParametersDOCUMENTELABORATIONSTATECOPIAPR;
  }




   /**
   * Constant MassiveScanWebSimpleArxiuRequiredParameters_DOCUMENTELABORATIONSTATE_ALTRES
   * @return massiveScanWebSimpleArxiuRequiredParametersDOCUMENTELABORATIONSTATEALTRES
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_ARXIU_REQUIRED_PARAMETERS_D_O_C_U_M_E_N_T_E_L_A_B_O_R_A_T_I_O_N_S_T_A_T_E_A_L_T_R_E_S)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getMassiveScanWebSimpleArxiuRequiredParametersDOCUMENTELABORATIONSTATEALTRES() {
    return massiveScanWebSimpleArxiuRequiredParametersDOCUMENTELABORATIONSTATEALTRES;
  }




   /**
   * Constant MassiveScanWebSimpleScannedFileInfo_FORMAT_FILE_PDF
   * @return massiveScanWebSimpleScannedFileInfoFORMATFILEPDF
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_SCANNED_FILE_INFO_F_O_R_M_A_T_F_I_L_E_P_D_F)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getMassiveScanWebSimpleScannedFileInfoFORMATFILEPDF() {
    return massiveScanWebSimpleScannedFileInfoFORMATFILEPDF;
  }




   /**
   * Constant MassiveScanWebSimpleScannedFileInfo_FORMAT_FILE_JPG
   * @return massiveScanWebSimpleScannedFileInfoFORMATFILEJPG
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_SCANNED_FILE_INFO_F_O_R_M_A_T_F_I_L_E_J_P_G)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getMassiveScanWebSimpleScannedFileInfoFORMATFILEJPG() {
    return massiveScanWebSimpleScannedFileInfoFORMATFILEJPG;
  }




   /**
   * Constant MassiveScanWebSimpleScannedFileInfo_FORMAT_FILE_TIFF
   * @return massiveScanWebSimpleScannedFileInfoFORMATFILETIFF
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_SCANNED_FILE_INFO_F_O_R_M_A_T_F_I_L_E_T_I_F_F)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getMassiveScanWebSimpleScannedFileInfoFORMATFILETIFF() {
    return massiveScanWebSimpleScannedFileInfoFORMATFILETIFF;
  }




   /**
   * Constant MassiveScanWebSimpleScannedFileInfo_FORMAT_FILE_PNG
   * @return massiveScanWebSimpleScannedFileInfoFORMATFILEPNG
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_SCANNED_FILE_INFO_F_O_R_M_A_T_F_I_L_E_P_N_G)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getMassiveScanWebSimpleScannedFileInfoFORMATFILEPNG() {
    return massiveScanWebSimpleScannedFileInfoFORMATFILEPNG;
  }




   /**
   * Constant MassiveScanWebSimpleScannedFileInfo_FORMAT_FILE_GIF
   * @return massiveScanWebSimpleScannedFileInfoFORMATFILEGIF
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_SCANNED_FILE_INFO_F_O_R_M_A_T_F_I_L_E_G_I_F)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getMassiveScanWebSimpleScannedFileInfoFORMATFILEGIF() {
    return massiveScanWebSimpleScannedFileInfoFORMATFILEGIF;
  }




   /**
   * Constant MassiveScanWebSimpleScannedFileInfo_PIXEL_TYPE_BLACK_WHITE
   * @return massiveScanWebSimpleScannedFileInfoPIXELTYPEBLACKWHITE
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_SCANNED_FILE_INFO_P_I_X_E_L_T_Y_P_E_B_L_A_C_K_W_H_I_T_E)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getMassiveScanWebSimpleScannedFileInfoPIXELTYPEBLACKWHITE() {
    return massiveScanWebSimpleScannedFileInfoPIXELTYPEBLACKWHITE;
  }




   /**
   * Constant MassiveScanWebSimpleScannedFileInfo_PIXEL_TYPE_GRAY
   * @return massiveScanWebSimpleScannedFileInfoPIXELTYPEGRAY
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_SCANNED_FILE_INFO_P_I_X_E_L_T_Y_P_E_G_R_A_Y)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getMassiveScanWebSimpleScannedFileInfoPIXELTYPEGRAY() {
    return massiveScanWebSimpleScannedFileInfoPIXELTYPEGRAY;
  }




   /**
   * Constant MassiveScanWebSimpleScannedFileInfo_PIXEL_TYPE_COLOR
   * @return massiveScanWebSimpleScannedFileInfoPIXELTYPECOLOR
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MASSIVE_SCAN_WEB_SIMPLE_SCANNED_FILE_INFO_P_I_X_E_L_T_Y_P_E_C_O_L_O_R)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getMassiveScanWebSimpleScannedFileInfoPIXELTYPECOLOR() {
    return massiveScanWebSimpleScannedFileInfoPIXELTYPECOLOR;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MassiveScanWebSimpleConstants massiveScanWebSimpleConstants = (MassiveScanWebSimpleConstants) o;
    return Objects.equals(this.massiveScanWebSimpleGetTransactionIdRequestVIEWFULLSCREEN, massiveScanWebSimpleConstants.massiveScanWebSimpleGetTransactionIdRequestVIEWFULLSCREEN) &&
        Objects.equals(this.massiveScanWebSimpleGetTransactionIdRequestVIEWIFRAME, massiveScanWebSimpleConstants.massiveScanWebSimpleGetTransactionIdRequestVIEWIFRAME) &&
        Objects.equals(this.massiveScanWebSimpleAvailableProfilePROFILETYPEONLYSCAN, massiveScanWebSimpleConstants.massiveScanWebSimpleAvailableProfilePROFILETYPEONLYSCAN) &&
        Objects.equals(this.massiveScanWebSimpleAvailableProfilePROFILETYPESCANANDSIGNATURE, massiveScanWebSimpleConstants.massiveScanWebSimpleAvailableProfilePROFILETYPESCANANDSIGNATURE) &&
        Objects.equals(this.massiveScanWebSimpleAvailableProfilePROFILETYPESCANANDSIGNATUREANDCUSTODY, massiveScanWebSimpleConstants.massiveScanWebSimpleAvailableProfilePROFILETYPESCANANDSIGNATUREANDCUSTODY) &&
        Objects.equals(this.massiveScanWebSimpleStatusSTATUSREQUESTEDID, massiveScanWebSimpleConstants.massiveScanWebSimpleStatusSTATUSREQUESTEDID) &&
        Objects.equals(this.massiveScanWebSimpleStatusSTATUSINPROGRESS, massiveScanWebSimpleConstants.massiveScanWebSimpleStatusSTATUSINPROGRESS) &&
        Objects.equals(this.massiveScanWebSimpleStatusSTATUSFINALOK, massiveScanWebSimpleConstants.massiveScanWebSimpleStatusSTATUSFINALOK) &&
        Objects.equals(this.massiveScanWebSimpleStatusSTATUSFINALERROR, massiveScanWebSimpleConstants.massiveScanWebSimpleStatusSTATUSFINALERROR) &&
        Objects.equals(this.massiveScanWebSimpleStatusSTATUSCANCELLED, massiveScanWebSimpleConstants.massiveScanWebSimpleStatusSTATUSCANCELLED) &&
        Objects.equals(this.massiveScanWebSimpleStatusSTATUSEXPIRED, massiveScanWebSimpleConstants.massiveScanWebSimpleStatusSTATUSEXPIRED) &&
        Objects.equals(this.massiveScanWebSimpleArxiuRequiredParametersDOCUMENTORIGENCIUTADA, massiveScanWebSimpleConstants.massiveScanWebSimpleArxiuRequiredParametersDOCUMENTORIGENCIUTADA) &&
        Objects.equals(this.massiveScanWebSimpleArxiuRequiredParametersDOCUMENTORIGENADMINISTRACIO, massiveScanWebSimpleConstants.massiveScanWebSimpleArxiuRequiredParametersDOCUMENTORIGENADMINISTRACIO) &&
        Objects.equals(this.massiveScanWebSimpleArxiuRequiredParametersDOCUMENTELABORATIONSTATEORIGINAL, massiveScanWebSimpleConstants.massiveScanWebSimpleArxiuRequiredParametersDOCUMENTELABORATIONSTATEORIGINAL) &&
        Objects.equals(this.massiveScanWebSimpleArxiuRequiredParametersDOCUMENTELABORATIONSTATECOPIACF, massiveScanWebSimpleConstants.massiveScanWebSimpleArxiuRequiredParametersDOCUMENTELABORATIONSTATECOPIACF) &&
        Objects.equals(this.massiveScanWebSimpleArxiuRequiredParametersDOCUMENTELABORATIONSTATECOPIADP, massiveScanWebSimpleConstants.massiveScanWebSimpleArxiuRequiredParametersDOCUMENTELABORATIONSTATECOPIADP) &&
        Objects.equals(this.massiveScanWebSimpleArxiuRequiredParametersDOCUMENTELABORATIONSTATECOPIAPR, massiveScanWebSimpleConstants.massiveScanWebSimpleArxiuRequiredParametersDOCUMENTELABORATIONSTATECOPIAPR) &&
        Objects.equals(this.massiveScanWebSimpleArxiuRequiredParametersDOCUMENTELABORATIONSTATEALTRES, massiveScanWebSimpleConstants.massiveScanWebSimpleArxiuRequiredParametersDOCUMENTELABORATIONSTATEALTRES) &&
        Objects.equals(this.massiveScanWebSimpleScannedFileInfoFORMATFILEPDF, massiveScanWebSimpleConstants.massiveScanWebSimpleScannedFileInfoFORMATFILEPDF) &&
        Objects.equals(this.massiveScanWebSimpleScannedFileInfoFORMATFILEJPG, massiveScanWebSimpleConstants.massiveScanWebSimpleScannedFileInfoFORMATFILEJPG) &&
        Objects.equals(this.massiveScanWebSimpleScannedFileInfoFORMATFILETIFF, massiveScanWebSimpleConstants.massiveScanWebSimpleScannedFileInfoFORMATFILETIFF) &&
        Objects.equals(this.massiveScanWebSimpleScannedFileInfoFORMATFILEPNG, massiveScanWebSimpleConstants.massiveScanWebSimpleScannedFileInfoFORMATFILEPNG) &&
        Objects.equals(this.massiveScanWebSimpleScannedFileInfoFORMATFILEGIF, massiveScanWebSimpleConstants.massiveScanWebSimpleScannedFileInfoFORMATFILEGIF) &&
        Objects.equals(this.massiveScanWebSimpleScannedFileInfoPIXELTYPEBLACKWHITE, massiveScanWebSimpleConstants.massiveScanWebSimpleScannedFileInfoPIXELTYPEBLACKWHITE) &&
        Objects.equals(this.massiveScanWebSimpleScannedFileInfoPIXELTYPEGRAY, massiveScanWebSimpleConstants.massiveScanWebSimpleScannedFileInfoPIXELTYPEGRAY) &&
        Objects.equals(this.massiveScanWebSimpleScannedFileInfoPIXELTYPECOLOR, massiveScanWebSimpleConstants.massiveScanWebSimpleScannedFileInfoPIXELTYPECOLOR);
  }

  @Override
  public int hashCode() {
    return Objects.hash(massiveScanWebSimpleGetTransactionIdRequestVIEWFULLSCREEN, massiveScanWebSimpleGetTransactionIdRequestVIEWIFRAME, massiveScanWebSimpleAvailableProfilePROFILETYPEONLYSCAN, massiveScanWebSimpleAvailableProfilePROFILETYPESCANANDSIGNATURE, massiveScanWebSimpleAvailableProfilePROFILETYPESCANANDSIGNATUREANDCUSTODY, massiveScanWebSimpleStatusSTATUSREQUESTEDID, massiveScanWebSimpleStatusSTATUSINPROGRESS, massiveScanWebSimpleStatusSTATUSFINALOK, massiveScanWebSimpleStatusSTATUSFINALERROR, massiveScanWebSimpleStatusSTATUSCANCELLED, massiveScanWebSimpleStatusSTATUSEXPIRED, massiveScanWebSimpleArxiuRequiredParametersDOCUMENTORIGENCIUTADA, massiveScanWebSimpleArxiuRequiredParametersDOCUMENTORIGENADMINISTRACIO, massiveScanWebSimpleArxiuRequiredParametersDOCUMENTELABORATIONSTATEORIGINAL, massiveScanWebSimpleArxiuRequiredParametersDOCUMENTELABORATIONSTATECOPIACF, massiveScanWebSimpleArxiuRequiredParametersDOCUMENTELABORATIONSTATECOPIADP, massiveScanWebSimpleArxiuRequiredParametersDOCUMENTELABORATIONSTATECOPIAPR, massiveScanWebSimpleArxiuRequiredParametersDOCUMENTELABORATIONSTATEALTRES, massiveScanWebSimpleScannedFileInfoFORMATFILEPDF, massiveScanWebSimpleScannedFileInfoFORMATFILEJPG, massiveScanWebSimpleScannedFileInfoFORMATFILETIFF, massiveScanWebSimpleScannedFileInfoFORMATFILEPNG, massiveScanWebSimpleScannedFileInfoFORMATFILEGIF, massiveScanWebSimpleScannedFileInfoPIXELTYPEBLACKWHITE, massiveScanWebSimpleScannedFileInfoPIXELTYPEGRAY, massiveScanWebSimpleScannedFileInfoPIXELTYPECOLOR);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MassiveScanWebSimpleConstants {\n");
    sb.append("    massiveScanWebSimpleGetTransactionIdRequestVIEWFULLSCREEN: ").append(toIndentedString(massiveScanWebSimpleGetTransactionIdRequestVIEWFULLSCREEN)).append("\n");
    sb.append("    massiveScanWebSimpleGetTransactionIdRequestVIEWIFRAME: ").append(toIndentedString(massiveScanWebSimpleGetTransactionIdRequestVIEWIFRAME)).append("\n");
    sb.append("    massiveScanWebSimpleAvailableProfilePROFILETYPEONLYSCAN: ").append(toIndentedString(massiveScanWebSimpleAvailableProfilePROFILETYPEONLYSCAN)).append("\n");
    sb.append("    massiveScanWebSimpleAvailableProfilePROFILETYPESCANANDSIGNATURE: ").append(toIndentedString(massiveScanWebSimpleAvailableProfilePROFILETYPESCANANDSIGNATURE)).append("\n");
    sb.append("    massiveScanWebSimpleAvailableProfilePROFILETYPESCANANDSIGNATUREANDCUSTODY: ").append(toIndentedString(massiveScanWebSimpleAvailableProfilePROFILETYPESCANANDSIGNATUREANDCUSTODY)).append("\n");
    sb.append("    massiveScanWebSimpleStatusSTATUSREQUESTEDID: ").append(toIndentedString(massiveScanWebSimpleStatusSTATUSREQUESTEDID)).append("\n");
    sb.append("    massiveScanWebSimpleStatusSTATUSINPROGRESS: ").append(toIndentedString(massiveScanWebSimpleStatusSTATUSINPROGRESS)).append("\n");
    sb.append("    massiveScanWebSimpleStatusSTATUSFINALOK: ").append(toIndentedString(massiveScanWebSimpleStatusSTATUSFINALOK)).append("\n");
    sb.append("    massiveScanWebSimpleStatusSTATUSFINALERROR: ").append(toIndentedString(massiveScanWebSimpleStatusSTATUSFINALERROR)).append("\n");
    sb.append("    massiveScanWebSimpleStatusSTATUSCANCELLED: ").append(toIndentedString(massiveScanWebSimpleStatusSTATUSCANCELLED)).append("\n");
    sb.append("    massiveScanWebSimpleStatusSTATUSEXPIRED: ").append(toIndentedString(massiveScanWebSimpleStatusSTATUSEXPIRED)).append("\n");
    sb.append("    massiveScanWebSimpleArxiuRequiredParametersDOCUMENTORIGENCIUTADA: ").append(toIndentedString(massiveScanWebSimpleArxiuRequiredParametersDOCUMENTORIGENCIUTADA)).append("\n");
    sb.append("    massiveScanWebSimpleArxiuRequiredParametersDOCUMENTORIGENADMINISTRACIO: ").append(toIndentedString(massiveScanWebSimpleArxiuRequiredParametersDOCUMENTORIGENADMINISTRACIO)).append("\n");
    sb.append("    massiveScanWebSimpleArxiuRequiredParametersDOCUMENTELABORATIONSTATEORIGINAL: ").append(toIndentedString(massiveScanWebSimpleArxiuRequiredParametersDOCUMENTELABORATIONSTATEORIGINAL)).append("\n");
    sb.append("    massiveScanWebSimpleArxiuRequiredParametersDOCUMENTELABORATIONSTATECOPIACF: ").append(toIndentedString(massiveScanWebSimpleArxiuRequiredParametersDOCUMENTELABORATIONSTATECOPIACF)).append("\n");
    sb.append("    massiveScanWebSimpleArxiuRequiredParametersDOCUMENTELABORATIONSTATECOPIADP: ").append(toIndentedString(massiveScanWebSimpleArxiuRequiredParametersDOCUMENTELABORATIONSTATECOPIADP)).append("\n");
    sb.append("    massiveScanWebSimpleArxiuRequiredParametersDOCUMENTELABORATIONSTATECOPIAPR: ").append(toIndentedString(massiveScanWebSimpleArxiuRequiredParametersDOCUMENTELABORATIONSTATECOPIAPR)).append("\n");
    sb.append("    massiveScanWebSimpleArxiuRequiredParametersDOCUMENTELABORATIONSTATEALTRES: ").append(toIndentedString(massiveScanWebSimpleArxiuRequiredParametersDOCUMENTELABORATIONSTATEALTRES)).append("\n");
    sb.append("    massiveScanWebSimpleScannedFileInfoFORMATFILEPDF: ").append(toIndentedString(massiveScanWebSimpleScannedFileInfoFORMATFILEPDF)).append("\n");
    sb.append("    massiveScanWebSimpleScannedFileInfoFORMATFILEJPG: ").append(toIndentedString(massiveScanWebSimpleScannedFileInfoFORMATFILEJPG)).append("\n");
    sb.append("    massiveScanWebSimpleScannedFileInfoFORMATFILETIFF: ").append(toIndentedString(massiveScanWebSimpleScannedFileInfoFORMATFILETIFF)).append("\n");
    sb.append("    massiveScanWebSimpleScannedFileInfoFORMATFILEPNG: ").append(toIndentedString(massiveScanWebSimpleScannedFileInfoFORMATFILEPNG)).append("\n");
    sb.append("    massiveScanWebSimpleScannedFileInfoFORMATFILEGIF: ").append(toIndentedString(massiveScanWebSimpleScannedFileInfoFORMATFILEGIF)).append("\n");
    sb.append("    massiveScanWebSimpleScannedFileInfoPIXELTYPEBLACKWHITE: ").append(toIndentedString(massiveScanWebSimpleScannedFileInfoPIXELTYPEBLACKWHITE)).append("\n");
    sb.append("    massiveScanWebSimpleScannedFileInfoPIXELTYPEGRAY: ").append(toIndentedString(massiveScanWebSimpleScannedFileInfoPIXELTYPEGRAY)).append("\n");
    sb.append("    massiveScanWebSimpleScannedFileInfoPIXELTYPECOLOR: ").append(toIndentedString(massiveScanWebSimpleScannedFileInfoPIXELTYPECOLOR)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

