/*
 * API REST INTERNA de DigitalIB
 * Conjunt de Serveis REST de DigitalIB per ser accedits des de l'interior
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: otae@fundaciobit.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.digitalib.apiinterna.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * MassiveScanWebSimpleProfileRequest
 */
@JsonPropertyOrder({
  MassiveScanWebSimpleProfileRequest.JSON_PROPERTY_PROFILE_CODE,
  MassiveScanWebSimpleProfileRequest.JSON_PROPERTY_LOCALE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.4.0")
public class MassiveScanWebSimpleProfileRequest {
  public static final String JSON_PROPERTY_PROFILE_CODE = "profileCode";
  private String profileCode;

  public static final String JSON_PROPERTY_LOCALE = "locale";
  private String locale;

  public MassiveScanWebSimpleProfileRequest() {
  }

  public MassiveScanWebSimpleProfileRequest profileCode(String profileCode) {
    
    this.profileCode = profileCode;
    return this;
  }

   /**
   * Get profileCode
   * @return profileCode
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROFILE_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getProfileCode() {
    return profileCode;
  }


  @JsonProperty(JSON_PROPERTY_PROFILE_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProfileCode(String profileCode) {
    this.profileCode = profileCode;
  }


  public MassiveScanWebSimpleProfileRequest locale(String locale) {
    
    this.locale = locale;
    return this;
  }

   /**
   * Get locale
   * @return locale
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOCALE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLocale() {
    return locale;
  }


  @JsonProperty(JSON_PROPERTY_LOCALE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLocale(String locale) {
    this.locale = locale;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MassiveScanWebSimpleProfileRequest massiveScanWebSimpleProfileRequest = (MassiveScanWebSimpleProfileRequest) o;
    return Objects.equals(this.profileCode, massiveScanWebSimpleProfileRequest.profileCode) &&
        Objects.equals(this.locale, massiveScanWebSimpleProfileRequest.locale);
  }

  @Override
  public int hashCode() {
    return Objects.hash(profileCode, locale);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MassiveScanWebSimpleProfileRequest {\n");
    sb.append("    profileCode: ").append(toIndentedString(profileCode)).append("\n");
    sb.append("    locale: ").append(toIndentedString(locale)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

