/*
 * API REST INTERNA de DigitalIB
 * Conjunt de Serveis REST de DigitalIB per ser accedits des de l'interior
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: otae@fundaciobit.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.digitalib.apiinterna.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * MassiveScanWebSimpleValidationInfo
 */
@JsonPropertyOrder({
  MassiveScanWebSimpleValidationInfo.JSON_PROPERTY_CHECK_ADMINISTRATION_I_D_OF_SIGNER,
  MassiveScanWebSimpleValidationInfo.JSON_PROPERTY_CHECK_DOCUMENT_MODIFICATIONS,
  MassiveScanWebSimpleValidationInfo.JSON_PROPERTY_CHECK_VALIDATION_SIGNATURE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class MassiveScanWebSimpleValidationInfo {
  public static final String JSON_PROPERTY_CHECK_ADMINISTRATION_I_D_OF_SIGNER = "checkAdministrationIDOfSigner";
  private Boolean checkAdministrationIDOfSigner;

  public static final String JSON_PROPERTY_CHECK_DOCUMENT_MODIFICATIONS = "checkDocumentModifications";
  private Boolean checkDocumentModifications;

  public static final String JSON_PROPERTY_CHECK_VALIDATION_SIGNATURE = "checkValidationSignature";
  private Boolean checkValidationSignature;

  public MassiveScanWebSimpleValidationInfo() {
  }

  public MassiveScanWebSimpleValidationInfo checkAdministrationIDOfSigner(Boolean checkAdministrationIDOfSigner) {
    
    this.checkAdministrationIDOfSigner = checkAdministrationIDOfSigner;
    return this;
  }

   /**
   * Get checkAdministrationIDOfSigner
   * @return checkAdministrationIDOfSigner
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CHECK_ADMINISTRATION_I_D_OF_SIGNER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean isCheckAdministrationIDOfSigner() {
    return checkAdministrationIDOfSigner;
  }


  @JsonProperty(JSON_PROPERTY_CHECK_ADMINISTRATION_I_D_OF_SIGNER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCheckAdministrationIDOfSigner(Boolean checkAdministrationIDOfSigner) {
    this.checkAdministrationIDOfSigner = checkAdministrationIDOfSigner;
  }


  public MassiveScanWebSimpleValidationInfo checkDocumentModifications(Boolean checkDocumentModifications) {
    
    this.checkDocumentModifications = checkDocumentModifications;
    return this;
  }

   /**
   * Get checkDocumentModifications
   * @return checkDocumentModifications
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CHECK_DOCUMENT_MODIFICATIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean isCheckDocumentModifications() {
    return checkDocumentModifications;
  }


  @JsonProperty(JSON_PROPERTY_CHECK_DOCUMENT_MODIFICATIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCheckDocumentModifications(Boolean checkDocumentModifications) {
    this.checkDocumentModifications = checkDocumentModifications;
  }


  public MassiveScanWebSimpleValidationInfo checkValidationSignature(Boolean checkValidationSignature) {
    
    this.checkValidationSignature = checkValidationSignature;
    return this;
  }

   /**
   * Get checkValidationSignature
   * @return checkValidationSignature
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CHECK_VALIDATION_SIGNATURE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean isCheckValidationSignature() {
    return checkValidationSignature;
  }


  @JsonProperty(JSON_PROPERTY_CHECK_VALIDATION_SIGNATURE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCheckValidationSignature(Boolean checkValidationSignature) {
    this.checkValidationSignature = checkValidationSignature;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MassiveScanWebSimpleValidationInfo massiveScanWebSimpleValidationInfo = (MassiveScanWebSimpleValidationInfo) o;
    return Objects.equals(this.checkAdministrationIDOfSigner, massiveScanWebSimpleValidationInfo.checkAdministrationIDOfSigner) &&
        Objects.equals(this.checkDocumentModifications, massiveScanWebSimpleValidationInfo.checkDocumentModifications) &&
        Objects.equals(this.checkValidationSignature, massiveScanWebSimpleValidationInfo.checkValidationSignature);
  }

  @Override
  public int hashCode() {
    return Objects.hash(checkAdministrationIDOfSigner, checkDocumentModifications, checkValidationSignature);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MassiveScanWebSimpleValidationInfo {\n");
    sb.append("    checkAdministrationIDOfSigner: ").append(toIndentedString(checkAdministrationIDOfSigner)).append("\n");
    sb.append("    checkDocumentModifications: ").append(toIndentedString(checkDocumentModifications)).append("\n");
    sb.append("    checkValidationSignature: ").append(toIndentedString(checkValidationSignature)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

