/*
 * API REST INTERNA de DigitalIB
 * Conjunt de Serveis REST de DigitalIB per ser accedits des de l'interior
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: otae@fundaciobit.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.digitalib.apiinterna.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Informació bàsica d&#39;una transacció d&#39;escaneig a DigitalIB.
 */
@JsonPropertyOrder({
  TransaccioInfo.JSON_PROPERTY_TRANSACCIO_I_D,
  TransaccioInfo.JSON_PROPERTY_TRANSACCIO_MULTIPLE_I_D,
  TransaccioInfo.JSON_PROPERTY_FUNCIONARI_USERNAME,
  TransaccioInfo.JSON_PROPERTY_APPNAME,
  TransaccioInfo.JSON_PROPERTY_USRNAME,
  TransaccioInfo.JSON_PROPERTY_FITXER_MIDA_BYTES,
  TransaccioInfo.JSON_PROPERTY_COLOR,
  TransaccioInfo.JSON_PROPERTY_RESOLUCIO,
  TransaccioInfo.JSON_PROPERTY_MIDA_PAPER,
  TransaccioInfo.JSON_PROPERTY_ESTAT,
  TransaccioInfo.JSON_PROPERTY_CODI_DIR3,
  TransaccioInfo.JSON_PROPERTY_CONFIGURACIO_GRUP_NOM,
  TransaccioInfo.JSON_PROPERTY_IDIOMA_DOCUMENT,
  TransaccioInfo.JSON_PROPERTY_DUPLEX,
  TransaccioInfo.JSON_PROPERTY_MISSATGE_ERROR,
  TransaccioInfo.JSON_PROPERTY_ORIGEN,
  TransaccioInfo.JSON_PROPERTY_TIPUS_DOCUMENTAL,
  TransaccioInfo.JSON_PROPERTY_DATA_CAPTURA
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class TransaccioInfo {
  public static final String JSON_PROPERTY_TRANSACCIO_I_D = "transaccioID";
  private Long transaccioID;

  public static final String JSON_PROPERTY_TRANSACCIO_MULTIPLE_I_D = "transaccioMultipleID";
  private Long transaccioMultipleID;

  public static final String JSON_PROPERTY_FUNCIONARI_USERNAME = "funcionariUsername";
  private String funcionariUsername;

  public static final String JSON_PROPERTY_APPNAME = "appname";
  private String appname;

  public static final String JSON_PROPERTY_USRNAME = "usrname";
  private String usrname;

  public static final String JSON_PROPERTY_FITXER_MIDA_BYTES = "fitxerMidaBytes";
  private Long fitxerMidaBytes;

  public static final String JSON_PROPERTY_COLOR = "color";
  private String color;

  public static final String JSON_PROPERTY_RESOLUCIO = "resolucio";
  private Integer resolucio;

  public static final String JSON_PROPERTY_MIDA_PAPER = "midaPaper";
  private String midaPaper;

  public static final String JSON_PROPERTY_ESTAT = "estat";
  private String estat;

  public static final String JSON_PROPERTY_CODI_DIR3 = "codiDir3";
  private String codiDir3;

  public static final String JSON_PROPERTY_CONFIGURACIO_GRUP_NOM = "configuracioGrupNom";
  private String configuracioGrupNom;

  public static final String JSON_PROPERTY_IDIOMA_DOCUMENT = "idiomaDocument";
  private String idiomaDocument;

  public static final String JSON_PROPERTY_DUPLEX = "duplex";
  private Boolean duplex;

  public static final String JSON_PROPERTY_MISSATGE_ERROR = "missatgeError";
  private String missatgeError;

  public static final String JSON_PROPERTY_ORIGEN = "origen";
  private String origen;

  public static final String JSON_PROPERTY_TIPUS_DOCUMENTAL = "tipusDocumental";
  private String tipusDocumental;

  public static final String JSON_PROPERTY_DATA_CAPTURA = "dataCaptura";
  private OffsetDateTime dataCaptura;

  public TransaccioInfo() {
  }

  public TransaccioInfo transaccioID(Long transaccioID) {
    
    this.transaccioID = transaccioID;
    return this;
  }

   /**
   * Get transaccioID
   * @return transaccioID
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TRANSACCIO_I_D)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getTransaccioID() {
    return transaccioID;
  }


  @JsonProperty(JSON_PROPERTY_TRANSACCIO_I_D)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTransaccioID(Long transaccioID) {
    this.transaccioID = transaccioID;
  }


  public TransaccioInfo transaccioMultipleID(Long transaccioMultipleID) {
    
    this.transaccioMultipleID = transaccioMultipleID;
    return this;
  }

   /**
   * Get transaccioMultipleID
   * @return transaccioMultipleID
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TRANSACCIO_MULTIPLE_I_D)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getTransaccioMultipleID() {
    return transaccioMultipleID;
  }


  @JsonProperty(JSON_PROPERTY_TRANSACCIO_MULTIPLE_I_D)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTransaccioMultipleID(Long transaccioMultipleID) {
    this.transaccioMultipleID = transaccioMultipleID;
  }


  public TransaccioInfo funcionariUsername(String funcionariUsername) {
    
    this.funcionariUsername = funcionariUsername;
    return this;
  }

   /**
   * Get funcionariUsername
   * @return funcionariUsername
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FUNCIONARI_USERNAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFuncionariUsername() {
    return funcionariUsername;
  }


  @JsonProperty(JSON_PROPERTY_FUNCIONARI_USERNAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFuncionariUsername(String funcionariUsername) {
    this.funcionariUsername = funcionariUsername;
  }


  public TransaccioInfo appname(String appname) {
    
    this.appname = appname;
    return this;
  }

   /**
   * Get appname
   * @return appname
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_APPNAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAppname() {
    return appname;
  }


  @JsonProperty(JSON_PROPERTY_APPNAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAppname(String appname) {
    this.appname = appname;
  }


  public TransaccioInfo usrname(String usrname) {
    
    this.usrname = usrname;
    return this;
  }

   /**
   * Get usrname
   * @return usrname
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_USRNAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUsrname() {
    return usrname;
  }


  @JsonProperty(JSON_PROPERTY_USRNAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUsrname(String usrname) {
    this.usrname = usrname;
  }


  public TransaccioInfo fitxerMidaBytes(Long fitxerMidaBytes) {
    
    this.fitxerMidaBytes = fitxerMidaBytes;
    return this;
  }

   /**
   * Get fitxerMidaBytes
   * @return fitxerMidaBytes
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FITXER_MIDA_BYTES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getFitxerMidaBytes() {
    return fitxerMidaBytes;
  }


  @JsonProperty(JSON_PROPERTY_FITXER_MIDA_BYTES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFitxerMidaBytes(Long fitxerMidaBytes) {
    this.fitxerMidaBytes = fitxerMidaBytes;
  }


  public TransaccioInfo color(String color) {
    
    this.color = color;
    return this;
  }

   /**
   * Mode en que es va fer l&#39;escaneig. Valors possibles: \&quot;B/N\&quot;,\&quot;Gris\&quot; o \&quot;Color\&quot;
   * @return color
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COLOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getColor() {
    return color;
  }


  @JsonProperty(JSON_PROPERTY_COLOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setColor(String color) {
    this.color = color;
  }


  public TransaccioInfo resolucio(Integer resolucio) {
    
    this.resolucio = resolucio;
    return this;
  }

   /**
   * Get resolucio
   * @return resolucio
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RESOLUCIO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getResolucio() {
    return resolucio;
  }


  @JsonProperty(JSON_PROPERTY_RESOLUCIO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setResolucio(Integer resolucio) {
    this.resolucio = resolucio;
  }


  public TransaccioInfo midaPaper(String midaPaper) {
    
    this.midaPaper = midaPaper;
    return this;
  }

   /**
   * Get midaPaper
   * @return midaPaper
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MIDA_PAPER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMidaPaper() {
    return midaPaper;
  }


  @JsonProperty(JSON_PROPERTY_MIDA_PAPER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMidaPaper(String midaPaper) {
    this.midaPaper = midaPaper;
  }


  public TransaccioInfo estat(String estat) {
    
    this.estat = estat;
    return this;
  }

   /**
   * Estat final de la transacció. Valors possibles: &#39;EXPIRAT&#39;,&#39;CANCELAT&#39;,&#39;ERROR&#39;,&#39;ID&#39;,&#39;ENPROGRES&#39;,&#39;OK&#39;
   * @return estat
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ESTAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEstat() {
    return estat;
  }


  @JsonProperty(JSON_PROPERTY_ESTAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEstat(String estat) {
    this.estat = estat;
  }


  public TransaccioInfo codiDir3(String codiDir3) {
    
    this.codiDir3 = codiDir3;
    return this;
  }

   /**
   * Get codiDir3
   * @return codiDir3
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CODI_DIR3)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCodiDir3() {
    return codiDir3;
  }


  @JsonProperty(JSON_PROPERTY_CODI_DIR3)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCodiDir3(String codiDir3) {
    this.codiDir3 = codiDir3;
  }


  public TransaccioInfo configuracioGrupNom(String configuracioGrupNom) {
    
    this.configuracioGrupNom = configuracioGrupNom;
    return this;
  }

   /**
   * Get configuracioGrupNom
   * @return configuracioGrupNom
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONFIGURACIO_GRUP_NOM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getConfiguracioGrupNom() {
    return configuracioGrupNom;
  }


  @JsonProperty(JSON_PROPERTY_CONFIGURACIO_GRUP_NOM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setConfiguracioGrupNom(String configuracioGrupNom) {
    this.configuracioGrupNom = configuracioGrupNom;
  }


  public TransaccioInfo idiomaDocument(String idiomaDocument) {
    
    this.idiomaDocument = idiomaDocument;
    return this;
  }

   /**
   * Get idiomaDocument
   * @return idiomaDocument
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IDIOMA_DOCUMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getIdiomaDocument() {
    return idiomaDocument;
  }


  @JsonProperty(JSON_PROPERTY_IDIOMA_DOCUMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIdiomaDocument(String idiomaDocument) {
    this.idiomaDocument = idiomaDocument;
  }


  public TransaccioInfo duplex(Boolean duplex) {
    
    this.duplex = duplex;
    return this;
  }

   /**
   * Get duplex
   * @return duplex
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DUPLEX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean isDuplex() {
    return duplex;
  }


  @JsonProperty(JSON_PROPERTY_DUPLEX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDuplex(Boolean duplex) {
    this.duplex = duplex;
  }


  public TransaccioInfo missatgeError(String missatgeError) {
    
    this.missatgeError = missatgeError;
    return this;
  }

   /**
   * Get missatgeError
   * @return missatgeError
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MISSATGE_ERROR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMissatgeError() {
    return missatgeError;
  }


  @JsonProperty(JSON_PROPERTY_MISSATGE_ERROR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMissatgeError(String missatgeError) {
    this.missatgeError = missatgeError;
  }


  public TransaccioInfo origen(String origen) {
    
    this.origen = origen;
    return this;
  }

   /**
   * Origen del Document. Valors possibles: Ciudadano o Administración en Castellà i Ciutadà o Administració en català
   * @return origen
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ORIGEN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOrigen() {
    return origen;
  }


  @JsonProperty(JSON_PROPERTY_ORIGEN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOrigen(String origen) {
    this.origen = origen;
  }


  public TransaccioInfo tipusDocumental(String tipusDocumental) {
    
    this.tipusDocumental = tipusDocumental;
    return this;
  }

   /**
   * Tipus Documental NTI. Valors possibles: &#39;TD01&#39;,&#39;TD02&#39;,&#39;TD03&#39;,&#39;TD04&#39;,&#39;TD05&#39;,&#39;TD06&#39;,&#39;TD07&#39;,&#39;TD08&#39;,&#39;TD09&#39;,&#39;TD10&#39;,&#39;TD11&#39;,&#39;TD12&#39;,&#39;TD13&#39;,&#39;TD14&#39;,&#39;TD15&#39;,&#39;TD16&#39;,&#39;TD17&#39;,&#39;TD18&#39;,&#39;TD19&#39;,&#39;TD20&#39;,&#39;TD51&#39;,&#39;TD52&#39;,&#39;TD53&#39;,&#39;TD54&#39;,&#39;TD55&#39;,&#39;TD56&#39;,&#39;TD57&#39;,&#39;TD58&#39;,&#39;TD59&#39;,&#39;TD60&#39;,&#39;TD61&#39;,&#39;TD62&#39;,&#39;TD63&#39;,&#39;TD64&#39;,&#39;TD65&#39;,&#39;TD66&#39;,&#39;TD67&#39;,&#39;TD68&#39;,&#39;TD69&#39;,&#39;TD99&#39;
   * @return tipusDocumental
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TIPUS_DOCUMENTAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTipusDocumental() {
    return tipusDocumental;
  }


  @JsonProperty(JSON_PROPERTY_TIPUS_DOCUMENTAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTipusDocumental(String tipusDocumental) {
    this.tipusDocumental = tipusDocumental;
  }


  public TransaccioInfo dataCaptura(OffsetDateTime dataCaptura) {
    
    this.dataCaptura = dataCaptura;
    return this;
  }

   /**
   * Data en que es va fer la transacció
   * @return dataCaptura
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_DATA_CAPTURA)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getDataCaptura() {
    return dataCaptura;
  }


  @JsonProperty(JSON_PROPERTY_DATA_CAPTURA)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDataCaptura(OffsetDateTime dataCaptura) {
    this.dataCaptura = dataCaptura;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransaccioInfo transaccioInfo = (TransaccioInfo) o;
    return Objects.equals(this.transaccioID, transaccioInfo.transaccioID) &&
        Objects.equals(this.transaccioMultipleID, transaccioInfo.transaccioMultipleID) &&
        Objects.equals(this.funcionariUsername, transaccioInfo.funcionariUsername) &&
        Objects.equals(this.appname, transaccioInfo.appname) &&
        Objects.equals(this.usrname, transaccioInfo.usrname) &&
        Objects.equals(this.fitxerMidaBytes, transaccioInfo.fitxerMidaBytes) &&
        Objects.equals(this.color, transaccioInfo.color) &&
        Objects.equals(this.resolucio, transaccioInfo.resolucio) &&
        Objects.equals(this.midaPaper, transaccioInfo.midaPaper) &&
        Objects.equals(this.estat, transaccioInfo.estat) &&
        Objects.equals(this.codiDir3, transaccioInfo.codiDir3) &&
        Objects.equals(this.configuracioGrupNom, transaccioInfo.configuracioGrupNom) &&
        Objects.equals(this.idiomaDocument, transaccioInfo.idiomaDocument) &&
        Objects.equals(this.duplex, transaccioInfo.duplex) &&
        Objects.equals(this.missatgeError, transaccioInfo.missatgeError) &&
        Objects.equals(this.origen, transaccioInfo.origen) &&
        Objects.equals(this.tipusDocumental, transaccioInfo.tipusDocumental) &&
        Objects.equals(this.dataCaptura, transaccioInfo.dataCaptura);
  }

  @Override
  public int hashCode() {
    return Objects.hash(transaccioID, transaccioMultipleID, funcionariUsername, appname, usrname, fitxerMidaBytes, color, resolucio, midaPaper, estat, codiDir3, configuracioGrupNom, idiomaDocument, duplex, missatgeError, origen, tipusDocumental, dataCaptura);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransaccioInfo {\n");
    sb.append("    transaccioID: ").append(toIndentedString(transaccioID)).append("\n");
    sb.append("    transaccioMultipleID: ").append(toIndentedString(transaccioMultipleID)).append("\n");
    sb.append("    funcionariUsername: ").append(toIndentedString(funcionariUsername)).append("\n");
    sb.append("    appname: ").append(toIndentedString(appname)).append("\n");
    sb.append("    usrname: ").append(toIndentedString(usrname)).append("\n");
    sb.append("    fitxerMidaBytes: ").append(toIndentedString(fitxerMidaBytes)).append("\n");
    sb.append("    color: ").append(toIndentedString(color)).append("\n");
    sb.append("    resolucio: ").append(toIndentedString(resolucio)).append("\n");
    sb.append("    midaPaper: ").append(toIndentedString(midaPaper)).append("\n");
    sb.append("    estat: ").append(toIndentedString(estat)).append("\n");
    sb.append("    codiDir3: ").append(toIndentedString(codiDir3)).append("\n");
    sb.append("    configuracioGrupNom: ").append(toIndentedString(configuracioGrupNom)).append("\n");
    sb.append("    idiomaDocument: ").append(toIndentedString(idiomaDocument)).append("\n");
    sb.append("    duplex: ").append(toIndentedString(duplex)).append("\n");
    sb.append("    missatgeError: ").append(toIndentedString(missatgeError)).append("\n");
    sb.append("    origen: ").append(toIndentedString(origen)).append("\n");
    sb.append("    tipusDocumental: ").append(toIndentedString(tipusDocumental)).append("\n");
    sb.append("    dataCaptura: ").append(toIndentedString(dataCaptura)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

