/*
 * API REST INTERNA de DigitalIB
 * Conjunt de Serveis REST de DigitalIB per ser accedits des de l'interior
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: otae@fundaciobit.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.digitalib.apiinterna.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import es.caib.digitalib.apiinterna.client.model.TransaccioInfo;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Transaccions
 */
@JsonPropertyOrder({
  Transaccions.JSON_PROPERTY_RESULTAT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class Transaccions {
  public static final String JSON_PROPERTY_RESULTAT = "resultat";
  private List<TransaccioInfo> resultat;

  public Transaccions() {
  }

  public Transaccions resultat(List<TransaccioInfo> resultat) {
    
    this.resultat = resultat;
    return this;
  }

  public Transaccions addResultatItem(TransaccioInfo resultatItem) {
    if (this.resultat == null) {
      this.resultat = new ArrayList<>();
    }
    this.resultat.add(resultatItem);
    return this;
  }

   /**
   * Get resultat
   * @return resultat
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RESULTAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<TransaccioInfo> getResultat() {
    return resultat;
  }


  @JsonProperty(JSON_PROPERTY_RESULTAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setResultat(List<TransaccioInfo> resultat) {
    this.resultat = resultat;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Transaccions transaccions = (Transaccions) o;
    return Objects.equals(this.resultat, transaccions.resultat);
  }

  @Override
  public int hashCode() {
    return Objects.hash(resultat);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Transaccions {\n");
    sb.append("    resultat: ").append(toIndentedString(resultat)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

