/*
 * API REST INTERNA de DigitalIB
 * Conjunt de Serveis REST de DigitalIB per ser accedits des de l'interior
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: otae@fundaciobit.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.digitalib.apiinterna.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import es.caib.digitalib.apiinterna.client.model.TransaccioInfo;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Transaccions
 */
@JsonPropertyOrder({
  Transaccions.JSON_PROPERTY_PAGE,
  Transaccions.JSON_PROPERTY_PAGE_SIZE,
  Transaccions.JSON_PROPERTY_TOTAL_PAGES,
  Transaccions.JSON_PROPERTY_TOTAL_COUNT,
  Transaccions.JSON_PROPERTY_ITEMS_RETURNED,
  Transaccions.JSON_PROPERTY_NEXT,
  Transaccions.JSON_PROPERTY_DATE_DOWNLOAD,
  Transaccions.JSON_PROPERTY_DATA
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class Transaccions {
  public static final String JSON_PROPERTY_PAGE = "page";
  private Integer page;

  public static final String JSON_PROPERTY_PAGE_SIZE = "page-size";
  private Integer pageSize;

  public static final String JSON_PROPERTY_TOTAL_PAGES = "total-pages";
  private Integer totalPages;

  public static final String JSON_PROPERTY_TOTAL_COUNT = "total-count";
  private Integer totalCount;

  public static final String JSON_PROPERTY_ITEMS_RETURNED = "items-returned";
  private Integer itemsReturned;

  public static final String JSON_PROPERTY_NEXT = "next";
  private String next;

  public static final String JSON_PROPERTY_DATE_DOWNLOAD = "date-download";
  private String dateDownload;

  public static final String JSON_PROPERTY_DATA = "data";
  private List<TransaccioInfo> data = new ArrayList<>();

  public Transaccions() {
  }

  public Transaccions page(Integer page) {
    
    this.page = page;
    return this;
  }

   /**
   * Número pàgina. Comença per 1.
   * @return page
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PAGE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getPage() {
    return page;
  }


  @JsonProperty(JSON_PROPERTY_PAGE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPage(Integer page) {
    this.page = page;
  }


  public Transaccions pageSize(Integer pageSize) {
    
    this.pageSize = pageSize;
    return this;
  }

   /**
   * Mida de pàgina
   * @return pageSize
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PAGE_SIZE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getPageSize() {
    return pageSize;
  }


  @JsonProperty(JSON_PROPERTY_PAGE_SIZE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPageSize(Integer pageSize) {
    this.pageSize = pageSize;
  }


  public Transaccions totalPages(Integer totalPages) {
    
    this.totalPages = totalPages;
    return this;
  }

   /**
   * Número total de pàgines
   * @return totalPages
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TOTAL_PAGES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getTotalPages() {
    return totalPages;
  }


  @JsonProperty(JSON_PROPERTY_TOTAL_PAGES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTotalPages(Integer totalPages) {
    this.totalPages = totalPages;
  }


  public Transaccions totalCount(Integer totalCount) {
    
    this.totalCount = totalCount;
    return this;
  }

   /**
   * Numero total d&#39;elements
   * @return totalCount
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TOTAL_COUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getTotalCount() {
    return totalCount;
  }


  @JsonProperty(JSON_PROPERTY_TOTAL_COUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTotalCount(Integer totalCount) {
    this.totalCount = totalCount;
  }


  public Transaccions itemsReturned(Integer itemsReturned) {
    
    this.itemsReturned = itemsReturned;
    return this;
  }

   /**
   * Numero d&#39;elements retornats
   * @return itemsReturned
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ITEMS_RETURNED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getItemsReturned() {
    return itemsReturned;
  }


  @JsonProperty(JSON_PROPERTY_ITEMS_RETURNED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setItemsReturned(Integer itemsReturned) {
    this.itemsReturned = itemsReturned;
  }


  public Transaccions next(String next) {
    
    this.next = next;
    return this;
  }

   /**
   * Si hi ha més elements, llavors retorna la URL a la següent pàgina de dades.
   * @return next
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NEXT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNext() {
    return next;
  }


  @JsonProperty(JSON_PROPERTY_NEXT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNext(String next) {
    this.next = next;
  }


  public Transaccions dateDownload(String dateDownload) {
    
    this.dateDownload = dateDownload;
    return this;
  }

   /**
   * Data i hora en que s&#39;han retornat les dades. Format ISO-8601
   * @return dateDownload
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_DATE_DOWNLOAD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getDateDownload() {
    return dateDownload;
  }


  @JsonProperty(JSON_PROPERTY_DATE_DOWNLOAD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDateDownload(String dateDownload) {
    this.dateDownload = dateDownload;
  }


  public Transaccions data(List<TransaccioInfo> data) {
    
    this.data = data;
    return this;
  }

  public Transaccions addDataItem(TransaccioInfo dataItem) {
    if (this.data == null) {
      this.data = new ArrayList<>();
    }
    this.data.add(dataItem);
    return this;
  }

   /**
   * Elements retornats
   * @return data
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_DATA)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<TransaccioInfo> getData() {
    return data;
  }


  @JsonProperty(JSON_PROPERTY_DATA)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setData(List<TransaccioInfo> data) {
    this.data = data;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Transaccions transaccions = (Transaccions) o;
    return Objects.equals(this.page, transaccions.page) &&
        Objects.equals(this.pageSize, transaccions.pageSize) &&
        Objects.equals(this.totalPages, transaccions.totalPages) &&
        Objects.equals(this.totalCount, transaccions.totalCount) &&
        Objects.equals(this.itemsReturned, transaccions.itemsReturned) &&
        Objects.equals(this.next, transaccions.next) &&
        Objects.equals(this.dateDownload, transaccions.dateDownload) &&
        Objects.equals(this.data, transaccions.data);
  }

  @Override
  public int hashCode() {
    return Objects.hash(page, pageSize, totalPages, totalCount, itemsReturned, next, dateDownload, data);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Transaccions {\n");
    sb.append("    page: ").append(toIndentedString(page)).append("\n");
    sb.append("    pageSize: ").append(toIndentedString(pageSize)).append("\n");
    sb.append("    totalPages: ").append(toIndentedString(totalPages)).append("\n");
    sb.append("    totalCount: ").append(toIndentedString(totalCount)).append("\n");
    sb.append("    itemsReturned: ").append(toIndentedString(itemsReturned)).append("\n");
    sb.append("    next: ").append(toIndentedString(next)).append("\n");
    sb.append("    dateDownload: ").append(toIndentedString(dateDownload)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

