/*
 * API REST EXTERNA de DigitalIB
 * Conjunt de Serveis REST de DigitalIB per ser accedits des de l'exterior
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: otae@fundaciobit.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.digitalib.apiexterna.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * MassiveScanWebSimpleSignatureParameters
 */
@JsonPropertyOrder({
  MassiveScanWebSimpleSignatureParameters.JSON_PROPERTY_FUNCTIONARY_FULL_NAME,
  MassiveScanWebSimpleSignatureParameters.JSON_PROPERTY_FUNCTIONARY_ADMINISTRATION_I_D,
  MassiveScanWebSimpleSignatureParameters.JSON_PROPERTY_FUNCTIONAY_D_I_R3_UNIT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class MassiveScanWebSimpleSignatureParameters {
  public static final String JSON_PROPERTY_FUNCTIONARY_FULL_NAME = "functionaryFullName";
  private String functionaryFullName;

  public static final String JSON_PROPERTY_FUNCTIONARY_ADMINISTRATION_I_D = "functionaryAdministrationID";
  private String functionaryAdministrationID;

  public static final String JSON_PROPERTY_FUNCTIONAY_D_I_R3_UNIT = "functionayDIR3Unit";
  private String functionayDIR3Unit;

  public MassiveScanWebSimpleSignatureParameters() {
  }

  public MassiveScanWebSimpleSignatureParameters functionaryFullName(String functionaryFullName) {
    
    this.functionaryFullName = functionaryFullName;
    return this;
  }

   /**
   * Get functionaryFullName
   * @return functionaryFullName
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FUNCTIONARY_FULL_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFunctionaryFullName() {
    return functionaryFullName;
  }


  @JsonProperty(JSON_PROPERTY_FUNCTIONARY_FULL_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFunctionaryFullName(String functionaryFullName) {
    this.functionaryFullName = functionaryFullName;
  }


  public MassiveScanWebSimpleSignatureParameters functionaryAdministrationID(String functionaryAdministrationID) {
    
    this.functionaryAdministrationID = functionaryAdministrationID;
    return this;
  }

   /**
   * Get functionaryAdministrationID
   * @return functionaryAdministrationID
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FUNCTIONARY_ADMINISTRATION_I_D)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFunctionaryAdministrationID() {
    return functionaryAdministrationID;
  }


  @JsonProperty(JSON_PROPERTY_FUNCTIONARY_ADMINISTRATION_I_D)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFunctionaryAdministrationID(String functionaryAdministrationID) {
    this.functionaryAdministrationID = functionaryAdministrationID;
  }


  public MassiveScanWebSimpleSignatureParameters functionayDIR3Unit(String functionayDIR3Unit) {
    
    this.functionayDIR3Unit = functionayDIR3Unit;
    return this;
  }

   /**
   * Get functionayDIR3Unit
   * @return functionayDIR3Unit
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FUNCTIONAY_D_I_R3_UNIT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFunctionayDIR3Unit() {
    return functionayDIR3Unit;
  }


  @JsonProperty(JSON_PROPERTY_FUNCTIONAY_D_I_R3_UNIT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFunctionayDIR3Unit(String functionayDIR3Unit) {
    this.functionayDIR3Unit = functionayDIR3Unit;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MassiveScanWebSimpleSignatureParameters massiveScanWebSimpleSignatureParameters = (MassiveScanWebSimpleSignatureParameters) o;
    return Objects.equals(this.functionaryFullName, massiveScanWebSimpleSignatureParameters.functionaryFullName) &&
        Objects.equals(this.functionaryAdministrationID, massiveScanWebSimpleSignatureParameters.functionaryAdministrationID) &&
        Objects.equals(this.functionayDIR3Unit, massiveScanWebSimpleSignatureParameters.functionayDIR3Unit);
  }

  @Override
  public int hashCode() {
    return Objects.hash(functionaryFullName, functionaryAdministrationID, functionayDIR3Unit);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MassiveScanWebSimpleSignatureParameters {\n");
    sb.append("    functionaryFullName: ").append(toIndentedString(functionaryFullName)).append("\n");
    sb.append("    functionaryAdministrationID: ").append(toIndentedString(functionaryAdministrationID)).append("\n");
    sb.append("    functionayDIR3Unit: ").append(toIndentedString(functionayDIR3Unit)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

