/*
 * API REST EXTERNA de DigitalIB
 * Conjunt de Serveis REST de DigitalIB per ser accedits des de l'exterior
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: otae@fundaciobit.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.digitalib.apiexterna.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import es.caib.digitalib.apiexterna.client.model.MassiveScanWebSimpleArxiuOptionalParameters;
import es.caib.digitalib.apiexterna.client.model.MassiveScanWebSimpleArxiuRequiredParameters;
import es.caib.digitalib.apiexterna.client.model.MassiveScanWebSimpleSignatureParameters;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * MassiveScanWebSimpleGetTransactionIdRequest
 */
@JsonPropertyOrder({
  MassiveScanWebSimpleGetTransactionIdRequest.JSON_PROPERTY_SCAN_WEB_PROFILE,
  MassiveScanWebSimpleGetTransactionIdRequest.JSON_PROPERTY_VIEW,
  MassiveScanWebSimpleGetTransactionIdRequest.JSON_PROPERTY_LANGUAGE_U_I,
  MassiveScanWebSimpleGetTransactionIdRequest.JSON_PROPERTY_TRANSACTION_NAME,
  MassiveScanWebSimpleGetTransactionIdRequest.JSON_PROPERTY_FUNCIONARI_USERNAME,
  MassiveScanWebSimpleGetTransactionIdRequest.JSON_PROPERTY_SIGNATURE_PARAMETERS,
  MassiveScanWebSimpleGetTransactionIdRequest.JSON_PROPERTY_ARXIU_REQUIRED_PARAMETERS,
  MassiveScanWebSimpleGetTransactionIdRequest.JSON_PROPERTY_ARXIU_OPTIONAL_PARAMETERS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class MassiveScanWebSimpleGetTransactionIdRequest {
  public static final String JSON_PROPERTY_SCAN_WEB_PROFILE = "scanWebProfile";
  private String scanWebProfile;

  public static final String JSON_PROPERTY_VIEW = "view";
  private Integer view = 1;

  public static final String JSON_PROPERTY_LANGUAGE_U_I = "languageUI";
  private String languageUI = "ca";

  public static final String JSON_PROPERTY_TRANSACTION_NAME = "transactionName";
  private String transactionName;

  public static final String JSON_PROPERTY_FUNCIONARI_USERNAME = "funcionariUsername";
  private String funcionariUsername;

  public static final String JSON_PROPERTY_SIGNATURE_PARAMETERS = "signatureParameters";
  private MassiveScanWebSimpleSignatureParameters signatureParameters;

  public static final String JSON_PROPERTY_ARXIU_REQUIRED_PARAMETERS = "arxiuRequiredParameters";
  private MassiveScanWebSimpleArxiuRequiredParameters arxiuRequiredParameters;

  public static final String JSON_PROPERTY_ARXIU_OPTIONAL_PARAMETERS = "arxiuOptionalParameters";
  private MassiveScanWebSimpleArxiuOptionalParameters arxiuOptionalParameters;

  public MassiveScanWebSimpleGetTransactionIdRequest() {
  }

  public MassiveScanWebSimpleGetTransactionIdRequest scanWebProfile(String scanWebProfile) {
    
    this.scanWebProfile = scanWebProfile;
    return this;
  }

   /**
   * Perfil d&#39;escaneig
   * @return scanWebProfile
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SCAN_WEB_PROFILE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getScanWebProfile() {
    return scanWebProfile;
  }


  @JsonProperty(JSON_PROPERTY_SCAN_WEB_PROFILE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setScanWebProfile(String scanWebProfile) {
    this.scanWebProfile = scanWebProfile;
  }


  public MassiveScanWebSimpleGetTransactionIdRequest view(Integer view) {
    
    this.view = view;
    return this;
  }

   /**
   * Tipus de Vista. Veure MassiveScanWebSimpleConstants.
   * @return view
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_VIEW)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getView() {
    return view;
  }


  @JsonProperty(JSON_PROPERTY_VIEW)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setView(Integer view) {
    this.view = view;
  }


  public MassiveScanWebSimpleGetTransactionIdRequest languageUI(String languageUI) {
    
    this.languageUI = languageUI;
    return this;
  }

   /**
   * Idioma del document en ISO 639-1. Valors permesos &#39;ca&#39; i &#39;es&#39;
   * @return languageUI
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_LANGUAGE_U_I)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getLanguageUI() {
    return languageUI;
  }


  @JsonProperty(JSON_PROPERTY_LANGUAGE_U_I)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLanguageUI(String languageUI) {
    this.languageUI = languageUI;
  }


  public MassiveScanWebSimpleGetTransactionIdRequest transactionName(String transactionName) {
    
    this.transactionName = transactionName;
    return this;
  }

   /**
   * Nom descriptiu de la transacció d&#39;escaneig.
   * @return transactionName
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TRANSACTION_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getTransactionName() {
    return transactionName;
  }


  @JsonProperty(JSON_PROPERTY_TRANSACTION_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTransactionName(String transactionName) {
    this.transactionName = transactionName;
  }


  public MassiveScanWebSimpleGetTransactionIdRequest funcionariUsername(String funcionariUsername) {
    
    this.funcionariUsername = funcionariUsername;
    return this;
  }

   /**
   * Username del funcionari.
   * @return funcionariUsername
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_FUNCIONARI_USERNAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getFuncionariUsername() {
    return funcionariUsername;
  }


  @JsonProperty(JSON_PROPERTY_FUNCIONARI_USERNAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFuncionariUsername(String funcionariUsername) {
    this.funcionariUsername = funcionariUsername;
  }


  public MassiveScanWebSimpleGetTransactionIdRequest signatureParameters(MassiveScanWebSimpleSignatureParameters signatureParameters) {
    
    this.signatureParameters = signatureParameters;
    return this;
  }

   /**
   * Get signatureParameters
   * @return signatureParameters
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SIGNATURE_PARAMETERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public MassiveScanWebSimpleSignatureParameters getSignatureParameters() {
    return signatureParameters;
  }


  @JsonProperty(JSON_PROPERTY_SIGNATURE_PARAMETERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSignatureParameters(MassiveScanWebSimpleSignatureParameters signatureParameters) {
    this.signatureParameters = signatureParameters;
  }


  public MassiveScanWebSimpleGetTransactionIdRequest arxiuRequiredParameters(MassiveScanWebSimpleArxiuRequiredParameters arxiuRequiredParameters) {
    
    this.arxiuRequiredParameters = arxiuRequiredParameters;
    return this;
  }

   /**
   * Get arxiuRequiredParameters
   * @return arxiuRequiredParameters
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ARXIU_REQUIRED_PARAMETERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public MassiveScanWebSimpleArxiuRequiredParameters getArxiuRequiredParameters() {
    return arxiuRequiredParameters;
  }


  @JsonProperty(JSON_PROPERTY_ARXIU_REQUIRED_PARAMETERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setArxiuRequiredParameters(MassiveScanWebSimpleArxiuRequiredParameters arxiuRequiredParameters) {
    this.arxiuRequiredParameters = arxiuRequiredParameters;
  }


  public MassiveScanWebSimpleGetTransactionIdRequest arxiuOptionalParameters(MassiveScanWebSimpleArxiuOptionalParameters arxiuOptionalParameters) {
    
    this.arxiuOptionalParameters = arxiuOptionalParameters;
    return this;
  }

   /**
   * Get arxiuOptionalParameters
   * @return arxiuOptionalParameters
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ARXIU_OPTIONAL_PARAMETERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public MassiveScanWebSimpleArxiuOptionalParameters getArxiuOptionalParameters() {
    return arxiuOptionalParameters;
  }


  @JsonProperty(JSON_PROPERTY_ARXIU_OPTIONAL_PARAMETERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setArxiuOptionalParameters(MassiveScanWebSimpleArxiuOptionalParameters arxiuOptionalParameters) {
    this.arxiuOptionalParameters = arxiuOptionalParameters;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MassiveScanWebSimpleGetTransactionIdRequest massiveScanWebSimpleGetTransactionIdRequest = (MassiveScanWebSimpleGetTransactionIdRequest) o;
    return Objects.equals(this.scanWebProfile, massiveScanWebSimpleGetTransactionIdRequest.scanWebProfile) &&
        Objects.equals(this.view, massiveScanWebSimpleGetTransactionIdRequest.view) &&
        Objects.equals(this.languageUI, massiveScanWebSimpleGetTransactionIdRequest.languageUI) &&
        Objects.equals(this.transactionName, massiveScanWebSimpleGetTransactionIdRequest.transactionName) &&
        Objects.equals(this.funcionariUsername, massiveScanWebSimpleGetTransactionIdRequest.funcionariUsername) &&
        Objects.equals(this.signatureParameters, massiveScanWebSimpleGetTransactionIdRequest.signatureParameters) &&
        Objects.equals(this.arxiuRequiredParameters, massiveScanWebSimpleGetTransactionIdRequest.arxiuRequiredParameters) &&
        Objects.equals(this.arxiuOptionalParameters, massiveScanWebSimpleGetTransactionIdRequest.arxiuOptionalParameters);
  }

  @Override
  public int hashCode() {
    return Objects.hash(scanWebProfile, view, languageUI, transactionName, funcionariUsername, signatureParameters, arxiuRequiredParameters, arxiuOptionalParameters);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MassiveScanWebSimpleGetTransactionIdRequest {\n");
    sb.append("    scanWebProfile: ").append(toIndentedString(scanWebProfile)).append("\n");
    sb.append("    view: ").append(toIndentedString(view)).append("\n");
    sb.append("    languageUI: ").append(toIndentedString(languageUI)).append("\n");
    sb.append("    transactionName: ").append(toIndentedString(transactionName)).append("\n");
    sb.append("    funcionariUsername: ").append(toIndentedString(funcionariUsername)).append("\n");
    sb.append("    signatureParameters: ").append(toIndentedString(signatureParameters)).append("\n");
    sb.append("    arxiuRequiredParameters: ").append(toIndentedString(arxiuRequiredParameters)).append("\n");
    sb.append("    arxiuOptionalParameters: ").append(toIndentedString(arxiuOptionalParameters)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

