/*
 * API REST INTERNA de DigitalIB - Versió
 * Conjunt de Serveis REST de DigitalIB per consultar la Versióde l'Aplicació.
 *
 * The version of the OpenAPI document: 1.0-SNAPSHOT
 * Contact: otae@fundaciobit.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.digitalib.api.interna.client.versio.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Informació de la Versió de DigitalIB
 */
@JsonPropertyOrder({
  Versio.JSON_PROPERTY_VERSIO,
  Versio.JSON_PROPERTY_LANGUAGE,
  Versio.JSON_PROPERTY_CAIB
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class Versio {
  public static final String JSON_PROPERTY_VERSIO = "versio";
  private String versio;

  public static final String JSON_PROPERTY_LANGUAGE = "language";
  private String language;

  public static final String JSON_PROPERTY_CAIB = "caib";
  private Boolean caib;

  public Versio() {
  }

  public Versio versio(String versio) {
    
    this.versio = versio;
    return this;
  }

   /**
   * Get versio
   * @return versio
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VERSIO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getVersio() {
    return versio;
  }


  @JsonProperty(JSON_PROPERTY_VERSIO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVersio(String versio) {
    this.versio = versio;
  }


  public Versio language(String language) {
    
    this.language = language;
    return this;
  }

   /**
   * Get language
   * @return language
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LANGUAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLanguage() {
    return language;
  }


  @JsonProperty(JSON_PROPERTY_LANGUAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLanguage(String language) {
    this.language = language;
  }


  public Versio caib(Boolean caib) {
    
    this.caib = caib;
    return this;
  }

   /**
   * Get caib
   * @return caib
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CAIB)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean isCaib() {
    return caib;
  }


  @JsonProperty(JSON_PROPERTY_CAIB)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCaib(Boolean caib) {
    this.caib = caib;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Versio versio = (Versio) o;
    return Objects.equals(this.versio, versio.versio) &&
        Objects.equals(this.language, versio.language) &&
        Objects.equals(this.caib, versio.caib);
  }

  @Override
  public int hashCode() {
    return Objects.hash(versio, language, caib);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Versio {\n");
    sb.append("    versio: ").append(toIndentedString(versio)).append("\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    caib: ").append(toIndentedString(caib)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

