/*
 * API REST INTERNA de DigitalIB - ApiMassiveScanWebSimple
 * Conjunt de Serveis REST de DigitalIB per la realització remota d'escanejos
 *
 * The version of the OpenAPI document: 1.0-SNAPSHOT
 * Contact: otae@fundaciobit.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.digitalib.api.interna.client.apimassivescanwebsimple.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * MassiveScanWebSimpleSubtransactionResultRequest
 */
@JsonPropertyOrder({
  MassiveScanWebSimpleSubtransactionResultRequest.JSON_PROPERTY_SUBTRANSACTION_I_D,
  MassiveScanWebSimpleSubtransactionResultRequest.JSON_PROPERTY_RETURN_SCANNED_FILE,
  MassiveScanWebSimpleSubtransactionResultRequest.JSON_PROPERTY_RETURN_SIGNED_FILE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class MassiveScanWebSimpleSubtransactionResultRequest {
  public static final String JSON_PROPERTY_SUBTRANSACTION_I_D = "subtransactionID";
  private String subtransactionID;

  public static final String JSON_PROPERTY_RETURN_SCANNED_FILE = "returnScannedFile";
  private Boolean returnScannedFile;

  public static final String JSON_PROPERTY_RETURN_SIGNED_FILE = "returnSignedFile";
  private Boolean returnSignedFile;

  public MassiveScanWebSimpleSubtransactionResultRequest() {
  }

  public MassiveScanWebSimpleSubtransactionResultRequest subtransactionID(String subtransactionID) {
    
    this.subtransactionID = subtransactionID;
    return this;
  }

   /**
   * Get subtransactionID
   * @return subtransactionID
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SUBTRANSACTION_I_D)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSubtransactionID() {
    return subtransactionID;
  }


  @JsonProperty(JSON_PROPERTY_SUBTRANSACTION_I_D)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSubtransactionID(String subtransactionID) {
    this.subtransactionID = subtransactionID;
  }


  public MassiveScanWebSimpleSubtransactionResultRequest returnScannedFile(Boolean returnScannedFile) {
    
    this.returnScannedFile = returnScannedFile;
    return this;
  }

   /**
   * Get returnScannedFile
   * @return returnScannedFile
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RETURN_SCANNED_FILE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean isReturnScannedFile() {
    return returnScannedFile;
  }


  @JsonProperty(JSON_PROPERTY_RETURN_SCANNED_FILE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReturnScannedFile(Boolean returnScannedFile) {
    this.returnScannedFile = returnScannedFile;
  }


  public MassiveScanWebSimpleSubtransactionResultRequest returnSignedFile(Boolean returnSignedFile) {
    
    this.returnSignedFile = returnSignedFile;
    return this;
  }

   /**
   * Get returnSignedFile
   * @return returnSignedFile
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RETURN_SIGNED_FILE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean isReturnSignedFile() {
    return returnSignedFile;
  }


  @JsonProperty(JSON_PROPERTY_RETURN_SIGNED_FILE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReturnSignedFile(Boolean returnSignedFile) {
    this.returnSignedFile = returnSignedFile;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MassiveScanWebSimpleSubtransactionResultRequest massiveScanWebSimpleSubtransactionResultRequest = (MassiveScanWebSimpleSubtransactionResultRequest) o;
    return Objects.equals(this.subtransactionID, massiveScanWebSimpleSubtransactionResultRequest.subtransactionID) &&
        Objects.equals(this.returnScannedFile, massiveScanWebSimpleSubtransactionResultRequest.returnScannedFile) &&
        Objects.equals(this.returnSignedFile, massiveScanWebSimpleSubtransactionResultRequest.returnSignedFile);
  }

  @Override
  public int hashCode() {
    return Objects.hash(subtransactionID, returnScannedFile, returnSignedFile);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MassiveScanWebSimpleSubtransactionResultRequest {\n");
    sb.append("    subtransactionID: ").append(toIndentedString(subtransactionID)).append("\n");
    sb.append("    returnScannedFile: ").append(toIndentedString(returnScannedFile)).append("\n");
    sb.append("    returnSignedFile: ").append(toIndentedString(returnSignedFile)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

