/*
 * API REST INTERNA de DigitalIB
 * Conjunt de Serveis REST de DigitalIB per ser accedits des de l'interior
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: otae@fundaciobit.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.digitalib.apiinterna.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * MassiveScanWebSimpleArxiuRequiredParameters
 */
@JsonPropertyOrder({
  MassiveScanWebSimpleArxiuRequiredParameters.JSON_PROPERTY_CITIZEN_ADMINISTRATION_I_D,
  MassiveScanWebSimpleArxiuRequiredParameters.JSON_PROPERTY_CITIZEN_FULL_NAME,
  MassiveScanWebSimpleArxiuRequiredParameters.JSON_PROPERTY_DOCUMENT_ELABORATION_STATE,
  MassiveScanWebSimpleArxiuRequiredParameters.JSON_PROPERTY_DOCUMENT_ORIGEN,
  MassiveScanWebSimpleArxiuRequiredParameters.JSON_PROPERTY_INTERESTED_PERSONS,
  MassiveScanWebSimpleArxiuRequiredParameters.JSON_PROPERTY_AFFECTED_ORGANISMS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.4.0")
public class MassiveScanWebSimpleArxiuRequiredParameters {
  public static final String JSON_PROPERTY_CITIZEN_ADMINISTRATION_I_D = "citizenAdministrationID";
  private String citizenAdministrationID;

  public static final String JSON_PROPERTY_CITIZEN_FULL_NAME = "citizenFullName";
  private String citizenFullName;

  public static final String JSON_PROPERTY_DOCUMENT_ELABORATION_STATE = "documentElaborationState";
  private String documentElaborationState;

  public static final String JSON_PROPERTY_DOCUMENT_ORIGEN = "documentOrigen";
  private Integer documentOrigen;

  public static final String JSON_PROPERTY_INTERESTED_PERSONS = "interestedPersons";
  private List<String> interestedPersons;

  public static final String JSON_PROPERTY_AFFECTED_ORGANISMS = "affectedOrganisms";
  private List<String> affectedOrganisms;

  public MassiveScanWebSimpleArxiuRequiredParameters() {
  }

  public MassiveScanWebSimpleArxiuRequiredParameters citizenAdministrationID(String citizenAdministrationID) {
    
    this.citizenAdministrationID = citizenAdministrationID;
    return this;
  }

   /**
   * Get citizenAdministrationID
   * @return citizenAdministrationID
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CITIZEN_ADMINISTRATION_I_D)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCitizenAdministrationID() {
    return citizenAdministrationID;
  }


  @JsonProperty(JSON_PROPERTY_CITIZEN_ADMINISTRATION_I_D)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCitizenAdministrationID(String citizenAdministrationID) {
    this.citizenAdministrationID = citizenAdministrationID;
  }


  public MassiveScanWebSimpleArxiuRequiredParameters citizenFullName(String citizenFullName) {
    
    this.citizenFullName = citizenFullName;
    return this;
  }

   /**
   * Get citizenFullName
   * @return citizenFullName
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CITIZEN_FULL_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCitizenFullName() {
    return citizenFullName;
  }


  @JsonProperty(JSON_PROPERTY_CITIZEN_FULL_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCitizenFullName(String citizenFullName) {
    this.citizenFullName = citizenFullName;
  }


  public MassiveScanWebSimpleArxiuRequiredParameters documentElaborationState(String documentElaborationState) {
    
    this.documentElaborationState = documentElaborationState;
    return this;
  }

   /**
   * Get documentElaborationState
   * @return documentElaborationState
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DOCUMENT_ELABORATION_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDocumentElaborationState() {
    return documentElaborationState;
  }


  @JsonProperty(JSON_PROPERTY_DOCUMENT_ELABORATION_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDocumentElaborationState(String documentElaborationState) {
    this.documentElaborationState = documentElaborationState;
  }


  public MassiveScanWebSimpleArxiuRequiredParameters documentOrigen(Integer documentOrigen) {
    
    this.documentOrigen = documentOrigen;
    return this;
  }

   /**
   * Get documentOrigen
   * @return documentOrigen
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DOCUMENT_ORIGEN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getDocumentOrigen() {
    return documentOrigen;
  }


  @JsonProperty(JSON_PROPERTY_DOCUMENT_ORIGEN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDocumentOrigen(Integer documentOrigen) {
    this.documentOrigen = documentOrigen;
  }


  public MassiveScanWebSimpleArxiuRequiredParameters interestedPersons(List<String> interestedPersons) {
    
    this.interestedPersons = interestedPersons;
    return this;
  }

  public MassiveScanWebSimpleArxiuRequiredParameters addInterestedPersonsItem(String interestedPersonsItem) {
    if (this.interestedPersons == null) {
      this.interestedPersons = new ArrayList<>();
    }
    this.interestedPersons.add(interestedPersonsItem);
    return this;
  }

   /**
   * Get interestedPersons
   * @return interestedPersons
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INTERESTED_PERSONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getInterestedPersons() {
    return interestedPersons;
  }


  @JsonProperty(JSON_PROPERTY_INTERESTED_PERSONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInterestedPersons(List<String> interestedPersons) {
    this.interestedPersons = interestedPersons;
  }


  public MassiveScanWebSimpleArxiuRequiredParameters affectedOrganisms(List<String> affectedOrganisms) {
    
    this.affectedOrganisms = affectedOrganisms;
    return this;
  }

  public MassiveScanWebSimpleArxiuRequiredParameters addAffectedOrganismsItem(String affectedOrganismsItem) {
    if (this.affectedOrganisms == null) {
      this.affectedOrganisms = new ArrayList<>();
    }
    this.affectedOrganisms.add(affectedOrganismsItem);
    return this;
  }

   /**
   * Get affectedOrganisms
   * @return affectedOrganisms
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AFFECTED_ORGANISMS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getAffectedOrganisms() {
    return affectedOrganisms;
  }


  @JsonProperty(JSON_PROPERTY_AFFECTED_ORGANISMS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAffectedOrganisms(List<String> affectedOrganisms) {
    this.affectedOrganisms = affectedOrganisms;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MassiveScanWebSimpleArxiuRequiredParameters massiveScanWebSimpleArxiuRequiredParameters = (MassiveScanWebSimpleArxiuRequiredParameters) o;
    return Objects.equals(this.citizenAdministrationID, massiveScanWebSimpleArxiuRequiredParameters.citizenAdministrationID) &&
        Objects.equals(this.citizenFullName, massiveScanWebSimpleArxiuRequiredParameters.citizenFullName) &&
        Objects.equals(this.documentElaborationState, massiveScanWebSimpleArxiuRequiredParameters.documentElaborationState) &&
        Objects.equals(this.documentOrigen, massiveScanWebSimpleArxiuRequiredParameters.documentOrigen) &&
        Objects.equals(this.interestedPersons, massiveScanWebSimpleArxiuRequiredParameters.interestedPersons) &&
        Objects.equals(this.affectedOrganisms, massiveScanWebSimpleArxiuRequiredParameters.affectedOrganisms);
  }

  @Override
  public int hashCode() {
    return Objects.hash(citizenAdministrationID, citizenFullName, documentElaborationState, documentOrigen, interestedPersons, affectedOrganisms);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MassiveScanWebSimpleArxiuRequiredParameters {\n");
    sb.append("    citizenAdministrationID: ").append(toIndentedString(citizenAdministrationID)).append("\n");
    sb.append("    citizenFullName: ").append(toIndentedString(citizenFullName)).append("\n");
    sb.append("    documentElaborationState: ").append(toIndentedString(documentElaborationState)).append("\n");
    sb.append("    documentOrigen: ").append(toIndentedString(documentOrigen)).append("\n");
    sb.append("    interestedPersons: ").append(toIndentedString(interestedPersons)).append("\n");
    sb.append("    affectedOrganisms: ").append(toIndentedString(affectedOrganisms)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

