openapi: 3.0.1
info:
  contact:
    email: otae@fundaciobit.org
    name: Departament de Govern Digital a la Fundació Bit
    url: http://otae.fundaciobit.org
  description: Conjunt de Serveis REST de DigitalIB per ser accedits des de l'exterior
  license:
    name: License Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0
  title: API REST EXTERNA de DigitalIB
  version: 1.0.0
externalDocs:
  description: Java Client (GovernIB Github)
  url: https://github.com/GovernIB/digitalib/tree/digitalib-1.0/digitalib-api-externa-client
servers:
- url: /digitalibapi/externa
- url: http://localhost:8080/digitalibapi/externa
- url: https://dev.caib.es/digitalibapi/externa
- url: https://proves.caib.es/digitalibapi/externa
- url: https://se.caib.es/digitalibapi/externa
- url: https://www.caib.es/digitalibapi/externa
tags:
- description: Exemple de Servei JSON d'accés Públic
  name: Versio
paths:
  /public/exemplepublic/versio:
    get:
      operationId: versio
      parameters:
      - description: Codi de l'idioma
        example: ca
        explode: true
        in: query
        name: idioma
        required: false
        schema:
          pattern: ^ca|es$
          type: string
        style: form
      responses:
        "404":
          content:
            application/json: {}
          description: Paràmetres incorrectes
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExamplePojo'
          description: Versió i idioma
      summary: Versio de l'Aplicació
      tags:
      - Versio
      x-accepts: application/json
components:
  schemas:
    ExamplePojo:
      example:
        versio: versio
      properties:
        versio:
          type: string
      type: object

