/*
 * API REST INTERNA de DigitalIB - Versió
 * Conjunt de Serveis REST de DigitalIB per consultar la Versióde l'Aplicació.
 *
 * The version of the OpenAPI document: 1.0-SNAPSHOT
 * Contact: otae@fundaciobit.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.digitalib.api.interna.client.versio.v1.api;

import es.caib.digitalib.api.interna.client.versio.v1.services.ApiException;
import es.caib.digitalib.api.interna.client.versio.v1.model.RestExceptionInfo;
import es.caib.digitalib.api.interna.client.versio.v1.model.Versio;
import org.junit.Test;
import org.junit.Ignore;
import org.junit.Assert;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for VersioApi
 */
public class VersioApiTest {

    private final VersioApi api = new VersioApi();

    /**
     * Versio de l&#39;Aplicació
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void versioTest() throws ApiException {
        //
        //String language = null;
        //
        //Versio response = api.versio(language);

        // TODO: test validations
    }
}
